// GENERATED FILE — do not edit.
//
// Written by scripts/generate-params.mjs from motionwave/manifests/dyn-05-console-eq.json.
// Edit the manifest and re-run `npm run params`. A hand edit here is exactly
// the second opinion the manifest exists to prevent, and `npm run params:check`
// fails the build if one is present.
import { defineParam } from '../../param/spec';
import type { ParamSpec } from '../../param/spec';
import { Taper, Unit } from '../../param/units';

/** Parameter ids, the same numbers the C++ enum carries. */
export const ConsoleEqParam = {
  Lineage: 1,
  Drive: 2,
  Output: 3,
  EqIn: 4,
  LowFrequency: 5,
  LowAmount: 6,
  MidFrequency: 7,
  MidAmount: 8,
  HighAmount: 9,
  HighPass: 10,
  BandOneFrequency: 11,
  BandOneAmount: 12,
  BandOneShape: 13,
  BandTwoFrequency: 14,
  BandTwoAmount: 15,
  BandThreeFrequency: 16,
  BandThreeAmount: 17,
  BandThreeShape: 18,
  BandPass: 19,
  Oversampling: 20,
} as const;

export type ConsoleEqParamId = (typeof ConsoleEqParam)[keyof typeof ConsoleEqParam];

/**
 * Every range, default and taper, straight from the manifest — which took them
 * from the Reference Spec Sheet. A control that sweeps a different range than
 * its sheet fails the unit's acceptance test on a number nobody checks by ear.
 */
export const consoleEqSpecs: readonly ParamSpec[] = [
  defineParam({
    id: ConsoleEqParam.Lineage,
    name: 'Lineage',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Inductor', 'Bridged-T'],
    smoothingMs: 0,
  }),
  defineParam({
    id: ConsoleEqParam.Drive,
    name: 'Drive',
    unit: Unit.Decibels,
    min: -20,
    max: 20,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: ConsoleEqParam.Output,
    name: 'Output',
    unit: Unit.Decibels,
    min: -20,
    max: 20,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: ConsoleEqParam.EqIn,
    name: 'EQ In',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 1,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Out', 'In'],
    smoothingMs: 0,
  }),
  defineParam({
    id: ConsoleEqParam.LowFrequency,
    name: 'Low Freq',
    unit: Unit.Choice,
    min: 0,
    max: 3,
    def: 2,
    taper: Taper.Stepped,
    steps: 4,
    choices: ['35 Hz', '60 Hz', '110 Hz', '220 Hz'],
    smoothingMs: 0,
  }),
  defineParam({
    id: ConsoleEqParam.LowAmount,
    name: 'Low',
    unit: Unit.Decibels,
    min: -16,
    max: 16,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 30,
  }),
  defineParam({
    id: ConsoleEqParam.MidFrequency,
    name: 'Mid Freq',
    unit: Unit.Choice,
    min: 0,
    max: 5,
    def: 2,
    taper: Taper.Stepped,
    steps: 6,
    choices: ['360 Hz', '700 Hz', '1.6 kHz', '3.2 kHz', '4.8 kHz', '7.2 kHz'],
    smoothingMs: 0,
  }),
  defineParam({
    id: ConsoleEqParam.MidAmount,
    name: 'Mid',
    unit: Unit.Decibels,
    min: -18,
    max: 18,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 30,
  }),
  defineParam({
    id: ConsoleEqParam.HighAmount,
    name: 'High',
    unit: Unit.Decibels,
    min: -16,
    max: 16,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 30,
  }),
  defineParam({
    id: ConsoleEqParam.HighPass,
    name: 'High-Pass',
    unit: Unit.Choice,
    min: 0,
    max: 4,
    def: 0,
    taper: Taper.Stepped,
    steps: 5,
    choices: ['Out', '50 Hz', '80 Hz', '160 Hz', '300 Hz'],
    smoothingMs: 0,
  }),
  defineParam({
    id: ConsoleEqParam.BandOneFrequency,
    name: 'Band 1 Freq',
    unit: Unit.Choice,
    min: 0,
    max: 4,
    def: 2,
    taper: Taper.Stepped,
    steps: 5,
    choices: ['50 Hz', '100 Hz', '200 Hz', '300 Hz', '400 Hz'],
    smoothingMs: 0,
  }),
  defineParam({
    id: ConsoleEqParam.BandOneAmount,
    name: 'Band 1',
    unit: Unit.Choice,
    min: 0,
    max: 10,
    def: 5,
    taper: Taper.Stepped,
    steps: 11,
    choices: ['-12', '-9', '-6', '-4', '-2', '0', '+2', '+4', '+6', '+9', '+12'],
    smoothingMs: 0,
  }),
  defineParam({
    id: ConsoleEqParam.BandOneShape,
    name: 'Band 1 Shape',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Peak', 'Shelf'],
    smoothingMs: 0,
  }),
  defineParam({
    id: ConsoleEqParam.BandTwoFrequency,
    name: 'Band 2 Freq',
    unit: Unit.Choice,
    min: 0,
    max: 4,
    def: 2,
    taper: Taper.Stepped,
    steps: 5,
    choices: ['400 Hz', '800 Hz', '1.5 kHz', '3 kHz', '5 kHz'],
    smoothingMs: 0,
  }),
  defineParam({
    id: ConsoleEqParam.BandTwoAmount,
    name: 'Band 2',
    unit: Unit.Choice,
    min: 0,
    max: 10,
    def: 5,
    taper: Taper.Stepped,
    steps: 11,
    choices: ['-12', '-9', '-6', '-4', '-2', '0', '+2', '+4', '+6', '+9', '+12'],
    smoothingMs: 0,
  }),
  defineParam({
    id: ConsoleEqParam.BandThreeFrequency,
    name: 'Band 3 Freq',
    unit: Unit.Choice,
    min: 0,
    max: 4,
    def: 2,
    taper: Taper.Stepped,
    steps: 5,
    choices: ['5 kHz', '7 kHz', '10 kHz', '12.5 kHz', '15 kHz'],
    smoothingMs: 0,
  }),
  defineParam({
    id: ConsoleEqParam.BandThreeAmount,
    name: 'Band 3',
    unit: Unit.Choice,
    min: 0,
    max: 10,
    def: 5,
    taper: Taper.Stepped,
    steps: 11,
    choices: ['-12', '-9', '-6', '-4', '-2', '0', '+2', '+4', '+6', '+9', '+12'],
    smoothingMs: 0,
  }),
  defineParam({
    id: ConsoleEqParam.BandThreeShape,
    name: 'Band 3 Shape',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Peak', 'Shelf'],
    smoothingMs: 0,
  }),
  defineParam({
    id: ConsoleEqParam.BandPass,
    name: 'Band-Pass',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Out', 'In'],
    smoothingMs: 0,
  }),
  defineParam({
    id: ConsoleEqParam.Oversampling,
    name: 'Oversampling',
    unit: Unit.Choice,
    min: 0,
    max: 3,
    def: 2,
    taper: Taper.Stepped,
    steps: 4,
    choices: ['Off', '2x', '4x', '8x'],
    smoothingMs: 0,
  }),
];

/**
 * What each parameter needs on the panel: which control, and what a screen
 * reader calls it. Not how it looks — colour and geometry are the face's, and
 * belong with the rest of the design language rather than in a generated file.
 *
 * `paramId` is a real id by construction. That is the half of D1 this file
 * exists to make unconstructible.
 */
export const consoleEqControls = [
  {
    id: 'lineage',
    role: 'switch',
    paramId: ConsoleEqParam.Lineage,
    accessibleName: 'Console lineage',
  },
  {
    id: 'drive',
    role: 'knob',
    paramId: ConsoleEqParam.Drive,
    accessibleName: 'Input drive',
  },
  {
    id: 'output',
    role: 'knob',
    paramId: ConsoleEqParam.Output,
    accessibleName: 'Output level',
  },
  {
    id: 'eq-in',
    role: 'switch',
    paramId: ConsoleEqParam.EqIn,
    accessibleName: 'EQ in circuit',
  },
  {
    id: 'low-frequency',
    role: 'switch',
    paramId: ConsoleEqParam.LowFrequency,
    accessibleName: 'Inductor low shelf frequency',
  },
  {
    id: 'low-amount',
    role: 'knob',
    paramId: ConsoleEqParam.LowAmount,
    accessibleName: 'Inductor low shelf amount',
  },
  {
    id: 'mid-frequency',
    role: 'switch',
    paramId: ConsoleEqParam.MidFrequency,
    accessibleName: 'Inductor mid bell frequency',
  },
  {
    id: 'mid-amount',
    role: 'knob',
    paramId: ConsoleEqParam.MidAmount,
    accessibleName: 'Inductor mid bell amount',
  },
  {
    id: 'high-amount',
    role: 'knob',
    paramId: ConsoleEqParam.HighAmount,
    accessibleName: 'Inductor high shelf amount',
  },
  {
    id: 'high-pass',
    role: 'switch',
    paramId: ConsoleEqParam.HighPass,
    accessibleName: 'High-pass filter corner',
  },
  {
    id: 'band-one-frequency',
    role: 'switch',
    paramId: ConsoleEqParam.BandOneFrequency,
    accessibleName: 'Bridged-T band 1 frequency',
  },
  {
    id: 'band-one-amount',
    role: 'switch',
    paramId: ConsoleEqParam.BandOneAmount,
    accessibleName: 'Bridged-T band 1 boost or cut',
  },
  {
    id: 'band-one-shape',
    role: 'switch',
    paramId: ConsoleEqParam.BandOneShape,
    accessibleName: 'Bridged-T band 1 peak or shelf',
  },
  {
    id: 'band-two-frequency',
    role: 'switch',
    paramId: ConsoleEqParam.BandTwoFrequency,
    accessibleName: 'Bridged-T band 2 frequency',
  },
  {
    id: 'band-two-amount',
    role: 'switch',
    paramId: ConsoleEqParam.BandTwoAmount,
    accessibleName: 'Bridged-T band 2 boost or cut',
  },
  {
    id: 'band-three-frequency',
    role: 'switch',
    paramId: ConsoleEqParam.BandThreeFrequency,
    accessibleName: 'Bridged-T band 3 frequency',
  },
  {
    id: 'band-three-amount',
    role: 'switch',
    paramId: ConsoleEqParam.BandThreeAmount,
    accessibleName: 'Bridged-T band 3 boost or cut',
  },
  {
    id: 'band-three-shape',
    role: 'switch',
    paramId: ConsoleEqParam.BandThreeShape,
    accessibleName: 'Bridged-T band 3 peak or shelf',
  },
  {
    id: 'band-pass',
    role: 'switch',
    paramId: ConsoleEqParam.BandPass,
    accessibleName: 'Band-pass filter',
  },
  {
    id: 'oversampling',
    role: 'switch',
    paramId: ConsoleEqParam.Oversampling,
    accessibleName: 'Oversampling tier',
  },
] as const;
