// Motion Wave — FET Limiter.
//
// `dyn-03`. A field-effect transistor as the variable element in a feedback
// loop, an amplifier that is always in circuit, and two transformers.
//
// **The detector runs inside the oversampling wrapper, and that is the whole
// architecture.** Its fastest attack is 20 µs, which is 0.96 samples at 48 kHz
// and 0.88 at 44.1 kHz — so a detector clocked at the host rate cannot express
// any setting faster than one sample and the entire top of the ATTACK control
// collapses onto one behaviour. That range is what this unit is known for. At
// 8× and 44.1 kHz the same 20 µs is seven sub-samples, and the control is a
// control again.
//
// Everything in the loop therefore runs at the inner rate: the detector, the
// FET, the amplifier and the output transformer. The loop closes on the
// previous *sub-sample*, which is 2.8 µs at 8× and 44.1 kHz rather than the
// 22.7 µs a host-rate loop would impose — and 22.7 µs of delay inside a 20 µs
// attack is not a fast attack, it is an oscillator.
//
// Two consequences the sheet asks for by name and this gets for free:
//
//   §4.1 The detector sees the *compressed* output, so the control signal
//        shrinks as reduction deepens and the effective attack slows and the
//        ratio softens with depth. Not compensated — it is the character.
//   §4   At the fastest settings the detector tracks *within* the cycle of a
//        bass note, so the gain is modulated at the signal frequency and the
//        distortion is generated by the detector rather than by any amplifier
//        stage. Test 11 confirms it is present and that it goes away as the
//        attack is slowed.
#pragma once

#include "../dsp/nonlinear/fet_divider.h"
#include "../dsp/nonlinear/magnetic_core.h"
#include "../dsp/nonlinear/oversampler.h"
#include "../dsp/nonlinear/specs.h"
#include "../dsp/peak_detector.h"
#include "../dsp/visual_state.h"
#include "../graph/node.h"

#include <cmath>
#include <cstdint>
#include <vector>

namespace mw::units {

namespace nl = dsp::nl;

inline constexpr int kFetChannels = 2;

/// The four buttons, and the state where they are all pressed at once.
enum class FetRatio { R4 = 0, R8 = 1, R12 = 2, R20 = 3, AllIn = 4 };

/// What the face draws.
struct FetLimiterFrame {
  float inputPeak = 0.0f;
  float outputPeak = 0.0f;
  float gainReductionDb = 0.0f;
  /// The timing network's charge, so a face can show it holding between hits.
  float detector = 0.0f;
};

using FetLimiterPublisher = dsp::FramePublisher<FetLimiterFrame>;

class FetLimiter : public Node {
 public:
  enum class Tier { Off = 0, X2 = 1, X4 = 2, X8 = 3 };

  // ---- configuration, off the audio thread ----

  /// Panel scale 1…7, fully clockwise being 7 and **fastest**. §9 test 3 exists
  /// to catch a model that gave this conventional sense.
  void setAttack(double position) noexcept {
    attack_ = position;
    dirty_ = true;
  }
  void setRelease(double position) noexcept {
    release_ = position;
    dirty_ = true;
  }
  /// ATTACK at OFF: the detector is out and the unit is a line amplifier.
  void setLimiting(bool on) noexcept { limiting_ = on; }
  void setRatio(FetRatio ratio) noexcept {
    ratio_ = ratio;
    dirty_ = true;
  }
  void setInputGain(double gain) noexcept { inputGain_ = gain; }
  void setOutputGain(double gain) noexcept { outputGain_ = gain; }
  void setTier(Tier tier) noexcept {
    if (tier != tier_) {
      tier_ = tier;
      dirty_ = true;
    }
  }
  void setVariance(float variance, std::uint32_t seed) noexcept {
    variance_ = variance;
    seed_ = seed;
    dirty_ = true;
  }
  void setNoise(double amplitude) noexcept { noise_ = amplitude; }
  void setBypass(bool bypass) noexcept { bypass_ = bypass; }

  // ---- Node ----

  void prepare(double sampleRate, int blockSize) override {
    sampleRate_ = sampleRate;
    blockSize_ = blockSize > 0 ? blockSize : 128;
    scratch_.assign(nl::oversamplerScratchFloats(8, blockSize_), 0.0f);
    for (int c = 0; c < kFetChannels; ++c) {
      nl::MagneticCore::Config input;
      input.saturationFlux *= 2.4f;
      inputCore_[c].prepare(sampleRate, input);
    }
    rebuild();
    reset();
  }

  void reset() override {
    for (int c = 0; c < kFetChannels; ++c) {
      inputCore_[c].reset();
      outputCore_[c].reset();
      amplifier_[c].reset();
      fet_[c].reset();
      detector_[c].reset();
      control_[c] = 0.0;
      applied_[c] = 0.0;
    }
    over2_.reset();
    over4_.reset();
    over8_.reset();
    rng_ = seed_ * 2654435761u + 1u;
    reductionDb_ = 0.0;
  }

  int latencySamples() const override { return latency_; }
  const char* name() const override { return "fet-limiter"; }

  void process(const ProcessContext& ctx) override {
    if (dirty_) rebuild();
    const AudioBuffer& in = ctx.inputs[0];
    AudioBuffer& out = ctx.outputs[0];
    const int channels = out.channelCount() < kFetChannels ? out.channelCount() : kFetChannels;
    if (bypass_) {
      out.copyFrom(in);
      publish(0.0f, 0.0f);
      return;
    }

    float inputPeak = 0.0f;
    float outputPeak = 0.0f;
    for (int c = 0; c < channels; ++c) {
      const float* source = in.channel(c);
      float* destination = out.channel(c);
      for (int i = 0; i < ctx.frames; ++i) {
        const double x = static_cast<double>(source[i]) * inputGain_;
        const float ax = static_cast<float>(x < 0.0 ? -x : x);
        if (ax > inputPeak) inputPeak = ax;
        float staged = inputCore_[c].process(static_cast<float>(x));

        // The loop, entirely at the inner rate. Everything the detector needs
        // to see and everything it controls is inside this lambda, so its
        // delay is one sub-sample rather than one sample.
        auto loop = [&](float v) {
          const double previous = control_[c];
          const double attenuated =
              static_cast<double>(fet_[c].process(v, static_cast<float>(previous)));
          const float amplified = amplifier_[c].process(static_cast<float>(attenuated));
          const float shaped = outputCore_[c].process(amplified);
          const double magnitude = static_cast<double>(shaped < 0.0f ? -shaped : shaped);
          // **The static law runs before the timing network, not after it.**
          //
          // The detector smooths the *control voltage*, which is what the
          // hardware's timing network does — it integrates a rectified control
          // signal, not the audio. Putting it the other way round makes a peak
          // detector hold a level from before the gain was applied, and then
          // every subsequent evaluation adds fresh reduction on top of a level
          // that no longer exists. Measured, that ran the element to its
          // maximum at every setting and every input, including 34 dB below
          // threshold, and held it there for as long as the release lasted.
          //
          // Smoothing the control instead means a clamped control decays with
          // the release and the loop re-evaluates, which is what settles it.
          const double wanted = desiredReductionDb(magnitude, applied_[c]);
          const double smoothed = limiting_ ? detector_[c].process(wanted) : 0.0;
          applied_[c] = smoothed;
          control_[c] =
              static_cast<double>(fet_[c].controlForReduction(static_cast<float>(smoothed)));
          return shaped;
        };
        float amplified = 0.0f;
        switch (tier_) {
          case Tier::Off: over1_.process(&staged, &amplified, 1, loop); break;
          case Tier::X2: over2_.process(&staged, &amplified, 1, loop); break;
          case Tier::X4: over4_.process(&staged, &amplified, 1, loop); break;
          case Tier::X8: over8_.process(&staged, &amplified, 1, loop); break;
        }

        double y = static_cast<double>(amplified) * outputGain_ + noise_ * nextNoise();
        const float sample = static_cast<float>(y);
        const float ay = sample < 0.0f ? -sample : sample;
        if (ay > outputPeak) outputPeak = ay;
        destination[i] = sample;
      }
    }
    // Relative to the element's resting gain. The bias trim already puts the
    // FET 1 dB into attenuation with no control at all — that is the documented
    // hardware calibration — and reporting it as a decibel of gain reduction
    // would mean the meter never reads zero and the line-amplifier mode looks
    // like it is limiting.
    reductionDb_ = static_cast<double>(fet_[0].gainDb(0.0f)) -
                   static_cast<double>(fet_[0].gainDb(static_cast<float>(control_[0])));
    publish(inputPeak, outputPeak);
  }

  const FetLimiterPublisher& visual() const noexcept { return visual_; }
  double gainReductionDb() const noexcept { return reductionDb_; }
  double detectorState() const noexcept { return detector_[0].state(); }

 private:
  /**
   * The control voltage the detector's charge produces, for the ratio in force.
   *
   * The ratio buttons change the feedback network's division, which changes the
   * *threshold* as well as the slope — and it raises it. That is §9 test 5, the
   * critical one: at a fixed input, switching from 4:1 to 20:1 must give
   * **less** gain reduction, not more, because the higher ratio sits on a
   * higher threshold. A model that treated the buttons as a slope alone gets
   * this exactly backwards and sounds wrong in the way people describe as "the
   * ratios do not do what they do on the hardware".
   *
   * In a feedback loop a control slope S produces a local ratio of 1 + S, which
   * is why the four buttons carry 3, 7, 11 and 19 rather than 4, 8, 12 and 20.
   */
  double desiredReductionDb(double magnitude, double appliedDb) const noexcept {
    if (!limiting_ || magnitude <= 0.0) return 0.0;
    // The detector sees the compressed output, so the level it reports is short
    // by whatever is currently being removed. Adding that back reconstructs the
    // input level, and asking for `S/(1+S)` of its excess lands directly on the
    // loop's own equilibrium — the same place a proportional loop of gain S
    // would settle, reached in one step instead of by ringing toward it.
    //
    // Both halves of that matter, and each was got wrong once. Applying the
    // full S instead makes the request 19× the excess, which pins the element
    // at its maximum on the first sample; and reconstructing against a
    // *level* the detector is holding — rather than against the control —
    // adds fresh reduction on top of a level that no longer exists, which
    // pinned it just as hard and for the whole release.
    //
    // What is not compensated is the timing, which §4.1 calls the character:
    // the detector still runs on the compressed output, so its level falls as
    // reduction deepens and its effective speed falls with it.
    const double levelDb = 20.0 * std::log10(magnitude) + appliedDb;
    const double over = levelDb - thresholdDb_;
    if (over <= 0.0) return 0.0;
    // A soft knee, narrowing as the ratio rises — §9 test 6 asks for the 4:1
    // knee to be at least 1.5× the 20:1 knee, which is what the hardware's own
    // feedback network does.
    const double knee = kneeDb_;
    const double shaped = over < knee ? (over * over) / (2.0 * knee) : over - knee * 0.5;
    double slope = slope_;
    if (ratio_ == FetRatio::AllIn) {
      // The four-button state's ratio is not a constant — §9 test 7 asserts the
      // slope 25 dB above threshold differs from the slope at 10 dB by at least
      // a fifth. Pressing every button drives the network into a region where
      // the division is level dependent.
      slope += 0.55 * shaped;
    }
    return shaped * slope / (1.0 + slope);
  }

  void rebuild() noexcept {
    nl::StageScratch slice{scratch_.data(), scratch_.size()};
    over1_.prepare(sampleRate_, blockSize_, slice);
    over2_.prepare(sampleRate_, blockSize_, slice);
    over4_.prepare(sampleRate_, blockSize_, slice);
    over8_.prepare(sampleRate_, blockSize_, slice);
    switch (tier_) {
      case Tier::Off: latency_ = over1_.latencySamples(); break;
      case Tier::X2: latency_ = over2_.latencySamples(); break;
      case Tier::X4: latency_ = over4_.latencySamples(); break;
      case Tier::X8: latency_ = over8_.latencySamples(); break;
    }
    const double innerRate = sampleRate_ * static_cast<double>(tierFactor(tier_));

    // Thresholds and slopes per button. The threshold offsets put 4:1 and 20:1
    // between 4 and 10 dB apart, which is what test 5 measures; the slopes are
    // (ratio − 1), which is what a feedback loop turns into the ratio.
    switch (ratio_) {
      case FetRatio::R4:
        slope_ = 3.0;
        thresholdDb_ = -37.0;
        kneeDb_ = 9.0;
        break;
      case FetRatio::R8:
        slope_ = 7.0;
        thresholdDb_ = -34.0;
        kneeDb_ = 7.0;
        break;
      case FetRatio::R12:
        slope_ = 11.0;
        thresholdDb_ = -31.0;
        kneeDb_ = 6.0;
        break;
      case FetRatio::R20:
        slope_ = 19.0;
        thresholdDb_ = -26.0;
        kneeDb_ = 4.5;
        break;
      case FetRatio::AllIn:
        // Every button in: the threshold drops a long way and the attack is
        // dramatically slowed. §9 test 8 calls that lag the single behaviour
        // that defines the state, and asks for it to be at least ten times the
        // 20:1 delay — the "reverse look-ahead" people describe.
        slope_ = 11.0;
        thresholdDb_ = -44.0;
        kneeDb_ = 14.0;
        break;
    }

    dsp::PeakDetectorConfig detector;
    detector.attackSeconds = dsp::panelScaleToSeconds(attack_, 0.000020, 0.000800);
    detector.releaseSeconds = dsp::panelScaleToSeconds(release_, 0.050, 1.100);
    if (ratio_ == FetRatio::AllIn) detector.attackSeconds *= 26.0;
    for (int c = 0; c < kFetChannels; ++c) detector_[c].prepare(innerRate, detector);

    // §6.2: the FET is the variable element and the source of the unit's
    // asymmetry — second-harmonic led, and rising steeply with reduction.
    nl::FetDivider::Config fet;
    nl::TriodeStage::Config amplifier;
    amplifier.drive = 0.16f;
    amplifier.bias = 0.030f;
    amplifier.restoreHz = 2.0f;
    nl::MagneticCore::Config outputCore;
    // §6.4: the output transformer has a feedback winding, so it distorts
    // *less* than the input one. A model that gave it more because it works at
    // a higher level would be reasoning correctly from the wrong circuit.
    outputCore.feedbackCancellation = 0.35f;
    if (variance_ > 0.0f) nl::param::applyVariance(variance_, seed_, amplifier, outputCore);
    for (int c = 0; c < kFetChannels; ++c) {
      fet_[c].prepare(innerRate, fet);
      amplifier_[c].prepare(innerRate, amplifier);
      outputCore_[c].prepare(innerRate, outputCore);
    }
    dirty_ = false;
  }

  static int tierFactor(Tier tier) noexcept {
    switch (tier) {
      case Tier::Off: return 1;
      case Tier::X2: return 2;
      case Tier::X4: return 4;
      case Tier::X8: return 8;
    }
    return 1;
  }

  double nextNoise() noexcept {
    rng_ = rng_ * 1664525u + 1013904223u;
    return static_cast<double>(rng_ >> 8) / 8388608.0 - 1.0;
  }

  void publish(float inputPeak, float outputPeak) noexcept {
    FetLimiterFrame frame;
    frame.inputPeak = inputPeak;
    frame.outputPeak = outputPeak;
    frame.gainReductionDb = static_cast<float>(reductionDb_);
    frame.detector = static_cast<float>(detector_[0].state());
    visual_.publish(frame);
  }

  nl::FetDivider fet_[kFetChannels];
  nl::TriodeStage amplifier_[kFetChannels];
  nl::MagneticCore inputCore_[kFetChannels];
  nl::MagneticCore outputCore_[kFetChannels];
  dsp::PeakDetector detector_[kFetChannels];
  nl::Oversampler<1> over1_;
  nl::Oversampler<2> over2_;
  nl::Oversampler<4> over4_;
  nl::Oversampler<8> over8_;
  FetLimiterPublisher visual_;

  std::vector<float> scratch_;
  double control_[kFetChannels] = {0.0, 0.0};
  double applied_[kFetChannels] = {0.0, 0.0};
  double sampleRate_ = 48000.0;
  double attack_ = 7.0;
  double release_ = 7.0;
  double inputGain_ = 1.0;
  double outputGain_ = 1.0;
  /// 81 dB below the threshold of limiting, per §8. rms, times √3.
  double noise_ = 3.0e-5;
  double slope_ = 3.0;
  double thresholdDb_ = -34.0;
  double kneeDb_ = 9.0;
  double reductionDb_ = 0.0;
  float variance_ = 0.0f;
  std::uint32_t seed_ = 1u;
  std::uint32_t rng_ = 1u;
  int blockSize_ = 128;
  int latency_ = 0;
  FetRatio ratio_ = FetRatio::R4;
  /// 8× by default, and not for polish. See the header note: at any lower
  /// factor the top of the ATTACK control stops being a control.
  Tier tier_ = Tier::X8;
  bool limiting_ = true;
  bool bypass_ = false;
  bool dirty_ = true;
};

}  // namespace mw::units
