/**
 * The matrix, and what it is allowed to claim.
 *
 * A defect here is a target reachable on a desktop and not on some smaller
 * thing, which is Directive 11 §5's definition and not a general "unreachable"
 * — a surface no form factor reaches is a different finding and is listed
 * separately, because it is usually a missing route rather than a mobile one.
 *
 * The exercised counters are printed above the defect list on purpose. The four
 * defects this sweep currently reports are all selection-dependent, and the
 * same run failed to tap-select a track eight times; a defect list whose
 * preconditions failed is a list of candidates, and saying so beside it is the
 * difference between a report and a claim.
 */
import { writeFileSync } from 'node:fs';
import { FORM_SCOPE, TARGET_SCOPE } from './targets.mjs';

/**
 * Write every output of a sweep: the two JSON files the mutation driver
 * reads, the matrix in `docs/audit/`, and the table on the terminal.
 *
 * @param rows one per form factor per target
 * @param exercised which branches this run actually entered
 */
export function writeMatrix(rows, exercised, { FORMS, TARGETS, JSON_ONLY }) {
  writeFileSync('reachability-out.json', JSON.stringify(rows, null, 2));
  writeFileSync('reachability-probe.json', JSON.stringify(exercised, null, 2));

  const forms = FORMS.map((f) => f.id);
  // A scoped run has no row for a form it did not sweep, and reading `.state`
  // off that undefined threw in the report rather than in the sweep — which
  // looked like the probe crashing when it had simply been asked for less.
  const cell = (form, target) =>
    rows.find((r) => r.form === form && r.target === target)?.state === 'REACHABLE';
  const onDesktop = new Set(TARGETS.filter((t) => cell('desktop', t.id)).map((t) => t.id));
  const defects = rows.filter(
    (r) => r.kind !== 'desktop' && r.state !== 'REACHABLE' && onDesktop.has(r.target),
  );
  const nowhere = TARGETS.filter((t) => !forms.some((f) => cell(f, t.id)));

  const grouped = defects.reduce((acc, d) => {
    const at = acc.find((a) => a.target === d.target);
    if (at) at.forms.push(d.form);
    else acc.push({ target: d.target, label: d.label, forms: [d.form] });
    return acc;
  }, []);

  const NL = '\n';
  const lines = [
    '# Reachability Matrix',
    '',
    '**Generated by `npm run reachability`. Do not edit by hand.**',
    '',
    'Directive 11 §5. Every surface, on every form factor, reached the way a user',
    "reaches it: navigate with the shell's own controls, select a track by tapping",
    'its header, and look. Nothing here is reached by calling a store.',
    '',
    '**`NOT REACHED` is not the same as unreachable.** It means this sweep did not',
    'get there, and the sweep performs navigation and selection only — it does not',
    'open a device by clicking an insert slot, or a take review by recording one. A',
    'row that is not reached on every form factor including desktop is almost',
    'certainly behind an interaction this sweep does not perform, and is listed',
    'separately below rather than counted as a mobile defect.',
    '',
    '**A defect is a surface reachable on desktop and not on something smaller.**',
    'That is the rule the directive sets: layout may differ, capability may not.',
    '',
    `| surface | ${forms.join(' | ')} |`,
    `| --- | ${forms.map(() => '---').join(' | ')} |`,
    ...TARGETS.map(
      (t) => `| ${t.label} | ${forms.map((f) => (cell(f, t.id) ? 'yes' : '—')).join(' | ')} |`,
    ),
    '',
    '## What the sweep managed, before any of it is read as a defect',
    '',
    'Every one of these is a way this sweep can under-report, so the numbers come',
    'first. A defect list standing on a walk that could not select a track is a',
    'list of the walk, not of the product.',
    '',
    '| | |',
    '| --- | --- |',
    `| tracks it could not select by tapping | ${exercised.tapFailures} |`,
    `| headers it had to scroll to | ${exercised.scrolls} |`,
    `| selections it had to re-assert | ${exercised.reasserts} |`,
    `| MIDI clips it opened | ${exercised.clipOpened} |`,
    '',
    '## Defects: reachable on desktop, not on a smaller screen',
    '',
    grouped.length === 0
      ? 'None.'
      : grouped.map((d) => `- **${d.label}** — ${d.forms.join(', ')}`).join(NL),
    '',
    '## Not reached anywhere, including desktop',
    '',
    'These need an interaction this sweep does not perform — opening a device from',
    'an insert slot, reviewing a take after recording one. They are work for the',
    'functional sweep rather than evidence of a missing feature.',
    '',
    nowhere.length === 0
      ? 'None.'
      : nowhere.map((t) => `- ${t.label} (\`${t.selector}\`)`).join(NL),
    '',
    '## How each was reached',
    '',
    '| surface | form | via |',
    '| --- | --- | --- |',
    ...rows
      .filter((r) => r.state === 'REACHABLE')
      .map((r) => `| ${r.label} | ${r.form} | ${r.via} |`),
    '',
  ];

  // A scoped run must not overwrite the matrix.
  //
  // It sweeps one form factor and a handful of targets, so what it would write is
  // a document that reads like a product with one screen size and five features.
  // The JSON above is still written, because that is what the mutation driver
  // compares; the committed audit is the whole sweep or it is nothing.
  if (FORM_SCOPE.length === 0 && TARGET_SCOPE.length === 0) {
    writeFileSync('docs/audit/REACHABILITY.md', lines.join(NL));
  } else if (!JSON_ONLY) {
    console.log(`${NL}Scoped run: docs/audit/REACHABILITY.md left alone.`);
  }

  if (JSON_ONLY) {
    console.log(JSON.stringify(rows, null, 2));
  } else {
    console.log(
      `${NL}${'surface'.padEnd(30)}${forms.map((f) => f.slice(0, 9).padEnd(11)).join('')}`,
    );
    console.log('-'.repeat(30 + forms.length * 11));
    for (const target of TARGETS) {
      const cells = forms.map((f) => (cell(f, target.id) ? 'yes' : 'NO').padEnd(11)).join('');
      console.log(`${target.label.padEnd(30)}${cells}`);
    }
    console.log(
      `${NL}${grouped.length} defect(s) — reachable on desktop, not on a smaller screen:`,
    );
    for (const d of grouped) console.log(`  ${d.label.padEnd(30)} ${d.forms.join(', ')}`);
    console.log(
      `${NL}${nowhere.length} surface(s) not reached anywhere; this sweep does not open them.`,
    );
    if (FORM_SCOPE.length === 0 && TARGET_SCOPE.length === 0) {
      console.log(`${NL}docs/audit/REACHABILITY.md written.`);
    }
  }
}
