// GENERATED FILE — do not edit.
//
// Written by scripts/generate-params.mjs from motionwave/manifests/fx-03-granular-delay.json.
// Edit the manifest and re-run `npm run params`. A hand edit here is exactly
// the second opinion the manifest exists to prevent, and `npm run params:check`
// fails the build if one is present.
import { defineParam } from '../../param/spec';
import type { ParamSpec } from '../../param/spec';
import { Taper, Unit } from '../../param/units';

/** Parameter ids, the same numbers the C++ enum carries. */
export const GranularDelayParam = {
  Mix: 1,
  Topology: 2,
  Cross: 3,
  TapCount: 4,
  Sync: 5,
  TimeMode: 6,
  Spacing: 7,
  Feedback: 8,
  FeedbackSource: 9,
  FeedbackTime: 10,
  FeedbackDivision: 11,
  FeedbackModifier: 12,
  LoopLowpass: 13,
  LoopHighpass: 14,
  Drive: 15,
  Character: 16,
  TimeChange: 17,
  Smear: 18,
  Ducking: 19,
  Width: 20,
  OutputTrim: 21,
  Quality: 22,
  Bypass: 23,
  Wear: 24,
  Bias: 25,
  Age: 26,
  Stages: 27,
  ClockWhine: 28,
  Tap1Time: 100,
  Tap1Division: 101,
  Tap1Modifier: 102,
  Tap1Level: 104,
  Tap1Pan: 105,
  Tap1Pitch: 106,
  Tap1Fine: 107,
  Tap1Filter: 108,
  Tap1Cutoff: 109,
  Tap1Q: 110,
  Tap1Reverse: 111,
  Tap1Mute: 112,
  Tap1Solo: 113,
  Tap2Time: 120,
  Tap2Division: 121,
  Tap2Modifier: 122,
  Tap2Ratio: 123,
  Tap2Level: 124,
  Tap2Pan: 125,
  Tap2Pitch: 126,
  Tap2Fine: 127,
  Tap2Filter: 128,
  Tap2Cutoff: 129,
  Tap2Q: 130,
  Tap2Reverse: 131,
  Tap2Mute: 132,
  Tap2Solo: 133,
  Tap3Time: 140,
  Tap3Division: 141,
  Tap3Modifier: 142,
  Tap3Ratio: 143,
  Tap3Level: 144,
  Tap3Pan: 145,
  Tap3Pitch: 146,
  Tap3Fine: 147,
  Tap3Filter: 148,
  Tap3Cutoff: 149,
  Tap3Q: 150,
  Tap3Reverse: 151,
  Tap3Mute: 152,
  Tap3Solo: 153,
  Tap4Time: 160,
  Tap4Division: 161,
  Tap4Modifier: 162,
  Tap4Ratio: 163,
  Tap4Level: 164,
  Tap4Pan: 165,
  Tap4Pitch: 166,
  Tap4Fine: 167,
  Tap4Filter: 168,
  Tap4Cutoff: 169,
  Tap4Q: 170,
  Tap4Reverse: 171,
  Tap4Mute: 172,
  Tap4Solo: 173,
  Tap5Time: 180,
  Tap5Division: 181,
  Tap5Modifier: 182,
  Tap5Ratio: 183,
  Tap5Level: 184,
  Tap5Pan: 185,
  Tap5Pitch: 186,
  Tap5Fine: 187,
  Tap5Filter: 188,
  Tap5Cutoff: 189,
  Tap5Q: 190,
  Tap5Reverse: 191,
  Tap5Mute: 192,
  Tap5Solo: 193,
  Tap6Time: 200,
  Tap6Division: 201,
  Tap6Modifier: 202,
  Tap6Ratio: 203,
  Tap6Level: 204,
  Tap6Pan: 205,
  Tap6Pitch: 206,
  Tap6Fine: 207,
  Tap6Filter: 208,
  Tap6Cutoff: 209,
  Tap6Q: 210,
  Tap6Reverse: 211,
  Tap6Mute: 212,
  Tap6Solo: 213,
  Tap7Time: 220,
  Tap7Division: 221,
  Tap7Modifier: 222,
  Tap7Ratio: 223,
  Tap7Level: 224,
  Tap7Pan: 225,
  Tap7Pitch: 226,
  Tap7Fine: 227,
  Tap7Filter: 228,
  Tap7Cutoff: 229,
  Tap7Q: 230,
  Tap7Reverse: 231,
  Tap7Mute: 232,
  Tap7Solo: 233,
  Tap8Time: 240,
  Tap8Division: 241,
  Tap8Modifier: 242,
  Tap8Ratio: 243,
  Tap8Level: 244,
  Tap8Pan: 245,
  Tap8Pitch: 246,
  Tap8Fine: 247,
  Tap8Filter: 248,
  Tap8Cutoff: 249,
  Tap8Q: 250,
  Tap8Reverse: 251,
  Tap8Mute: 252,
  Tap8Solo: 253,
} as const;

export type GranularDelayParamId = (typeof GranularDelayParam)[keyof typeof GranularDelayParam];

/**
 * Every range, default and taper, straight from the manifest — which took them
 * from the Reference Spec Sheet. A control that sweeps a different range than
 * its sheet fails the unit's acceptance test on a number nobody checks by ear.
 */
export const granularDelaySpecs: readonly ParamSpec[] = [
  defineParam({
    id: GranularDelayParam.Mix,
    name: 'Mix',
    unit: Unit.Percent,
    min: 0,
    max: 100,
    def: 30,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularDelayParam.Topology,
    name: 'Topology',
    unit: Unit.Choice,
    min: 0,
    max: 3,
    def: 0,
    taper: Taper.Stepped,
    steps: 4,
    choices: ['Dual', 'Ping-pong', 'Blend', 'Mono sum'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Cross,
    name: 'Cross',
    unit: Unit.Percent,
    min: 0,
    max: 100,
    def: 50,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularDelayParam.TapCount,
    name: 'Taps',
    unit: Unit.Choice,
    min: 0,
    max: 7,
    def: 3,
    taper: Taper.Stepped,
    steps: 8,
    choices: ['1', '2', '3', '4', '5', '6', '7', '8'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Sync,
    name: 'Sync',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 1,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.TimeMode,
    name: 'Tap times',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Absolute', 'Relative'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Spacing,
    name: 'Spacing',
    unit: Unit.Choice,
    min: 0,
    max: 3,
    def: 0,
    taper: Taper.Stepped,
    steps: 4,
    choices: ['Even', '1·2·3', '1·2·4', '1·3·4'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Feedback,
    name: 'Feedback',
    unit: Unit.Percent,
    min: 0,
    max: 130,
    def: 35,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularDelayParam.FeedbackSource,
    name: 'Feedback from',
    unit: Unit.Choice,
    min: 0,
    max: 2,
    def: 0,
    taper: Taper.Stepped,
    steps: 3,
    choices: ['Dedicated', 'First tap', 'Longest tap'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.FeedbackTime,
    name: 'Feedback time',
    unit: Unit.Milliseconds,
    min: 1,
    max: 8000,
    def: 250,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.FeedbackDivision,
    name: 'Feedback division',
    unit: Unit.Choice,
    min: 0,
    max: 9,
    def: 3,
    taper: Taper.Stepped,
    steps: 10,
    choices: ['1/64', '1/32', '1/16', '1/8', '1/4', '1/2', '1/1', '2 bars', '4 bars', '8 bars'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.FeedbackModifier,
    name: 'Feedback modifier',
    unit: Unit.Choice,
    min: 0,
    max: 2,
    def: 0,
    taper: Taper.Stepped,
    steps: 3,
    choices: ['Straight', 'Dotted', 'Triplet'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.LoopLowpass,
    name: 'Loop LP',
    unit: Unit.Hertz,
    min: 200,
    max: 20000,
    def: 6000,
    taper: Taper.Logarithmic,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularDelayParam.LoopHighpass,
    name: 'Loop HP',
    unit: Unit.Hertz,
    min: 20,
    max: 2000,
    def: 90,
    taper: Taper.Logarithmic,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularDelayParam.Drive,
    name: 'Drive',
    unit: Unit.Percent,
    min: 0,
    max: 100,
    def: 20,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularDelayParam.Character,
    name: 'Character',
    unit: Unit.Choice,
    min: 0,
    max: 2,
    def: 1,
    taper: Taper.Stepped,
    steps: 3,
    choices: ['Clean', 'Tape', 'BBD'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.TimeChange,
    name: 'Time change',
    unit: Unit.Choice,
    min: 0,
    max: 2,
    def: 1,
    taper: Taper.Stepped,
    steps: 3,
    choices: ['Tape', 'Digital', 'Instant'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Smear,
    name: 'Smear',
    unit: Unit.Percent,
    min: 0,
    max: 100,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Ducking,
    name: 'Ducking',
    unit: Unit.Percent,
    min: 0,
    max: 100,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularDelayParam.Width,
    name: 'Width',
    unit: Unit.Percent,
    min: 0,
    max: 200,
    def: 100,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularDelayParam.OutputTrim,
    name: 'Output trim',
    unit: Unit.Decibels,
    min: -24,
    max: 24,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularDelayParam.Quality,
    name: 'Quality',
    unit: Unit.Choice,
    min: 0,
    max: 2,
    def: 2,
    taper: Taper.Stepped,
    steps: 3,
    choices: ['Eco', 'Normal', 'High'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Bypass,
    name: 'Bypass',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Wear,
    name: 'Wear',
    unit: Unit.Choice,
    min: 0,
    max: 3,
    def: 1,
    taper: Taper.Stepped,
    steps: 4,
    choices: ['Clean', 'Studio', 'Vintage', 'Worn'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Bias,
    name: 'Bias',
    unit: Unit.Percent,
    min: 0,
    max: 100,
    def: 30,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Age,
    name: 'Age',
    unit: Unit.Percent,
    min: 0,
    max: 100,
    def: 20,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Stages,
    name: 'Stages',
    unit: Unit.Choice,
    min: 0,
    max: 2,
    def: 2,
    taper: Taper.Stepped,
    steps: 3,
    choices: ['1024', '2048', '4096'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.ClockWhine,
    name: 'Clock whine',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 1,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap1Time,
    name: 'Tap1 time',
    unit: Unit.Milliseconds,
    min: 1,
    max: 8000,
    def: 250,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap1Division,
    name: 'Tap1 division',
    unit: Unit.Choice,
    min: 0,
    max: 9,
    def: 3,
    taper: Taper.Stepped,
    steps: 10,
    choices: ['1/64', '1/32', '1/16', '1/8', '1/4', '1/2', '1/1', '2 bars', '4 bars', '8 bars'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap1Modifier,
    name: 'Tap1 modifier',
    unit: Unit.Choice,
    min: 0,
    max: 2,
    def: 0,
    taper: Taper.Stepped,
    steps: 3,
    choices: ['Straight', 'Dotted', 'Triplet'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap1Level,
    name: 'Tap1 level',
    unit: Unit.Decibels,
    min: -60,
    max: 6,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap1Pan,
    name: 'Tap1 pan',
    unit: Unit.Percent,
    min: -100,
    max: 100,
    def: -30,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap1Pitch,
    name: 'Tap1 pitch',
    unit: Unit.Semitones,
    min: -24,
    max: 24,
    def: 0,
    taper: Taper.Stepped,
    steps: 49,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap1Fine,
    name: 'Tap1 fine',
    unit: Unit.Cents,
    min: -50,
    max: 50,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap1Filter,
    name: 'Tap1 filter',
    unit: Unit.Choice,
    min: 0,
    max: 3,
    def: 0,
    taper: Taper.Stepped,
    steps: 4,
    choices: ['Off', 'LP', 'HP', 'BP'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap1Cutoff,
    name: 'Tap1 cutoff',
    unit: Unit.Hertz,
    min: 20,
    max: 20000,
    def: 20000,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap1Q,
    name: 'Tap1 Q',
    unit: Unit.Linear,
    min: 0.5,
    max: 8,
    def: 0.707,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap1Reverse,
    name: 'Tap1 reverse',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap1Mute,
    name: 'Tap1 mute',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap1Solo,
    name: 'Tap1 solo',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap2Time,
    name: 'Tap2 time',
    unit: Unit.Milliseconds,
    min: 1,
    max: 8000,
    def: 500,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap2Division,
    name: 'Tap2 division',
    unit: Unit.Choice,
    min: 0,
    max: 9,
    def: 4,
    taper: Taper.Stepped,
    steps: 10,
    choices: ['1/64', '1/32', '1/16', '1/8', '1/4', '1/2', '1/1', '2 bars', '4 bars', '8 bars'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap2Modifier,
    name: 'Tap2 modifier',
    unit: Unit.Choice,
    min: 0,
    max: 2,
    def: 0,
    taper: Taper.Stepped,
    steps: 3,
    choices: ['Straight', 'Dotted', 'Triplet'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap2Ratio,
    name: 'Tap2 ratio',
    unit: Unit.Choice,
    min: 0,
    max: 10,
    def: 0,
    taper: Taper.Stepped,
    steps: 11,
    choices: ['Auto', '×0.25', '×0.5', '×0.75', '×1', '×1.5', '×2', '×3', '×4', '×6', '×8'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap2Level,
    name: 'Tap2 level',
    unit: Unit.Decibels,
    min: -60,
    max: 6,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap2Pan,
    name: 'Tap2 pan',
    unit: Unit.Percent,
    min: -100,
    max: 100,
    def: 30,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap2Pitch,
    name: 'Tap2 pitch',
    unit: Unit.Semitones,
    min: -24,
    max: 24,
    def: 0,
    taper: Taper.Stepped,
    steps: 49,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap2Fine,
    name: 'Tap2 fine',
    unit: Unit.Cents,
    min: -50,
    max: 50,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap2Filter,
    name: 'Tap2 filter',
    unit: Unit.Choice,
    min: 0,
    max: 3,
    def: 0,
    taper: Taper.Stepped,
    steps: 4,
    choices: ['Off', 'LP', 'HP', 'BP'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap2Cutoff,
    name: 'Tap2 cutoff',
    unit: Unit.Hertz,
    min: 20,
    max: 20000,
    def: 20000,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap2Q,
    name: 'Tap2 Q',
    unit: Unit.Linear,
    min: 0.5,
    max: 8,
    def: 0.707,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap2Reverse,
    name: 'Tap2 reverse',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap2Mute,
    name: 'Tap2 mute',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap2Solo,
    name: 'Tap2 solo',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap3Time,
    name: 'Tap3 time',
    unit: Unit.Milliseconds,
    min: 1,
    max: 8000,
    def: 750,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap3Division,
    name: 'Tap3 division',
    unit: Unit.Choice,
    min: 0,
    max: 9,
    def: 4,
    taper: Taper.Stepped,
    steps: 10,
    choices: ['1/64', '1/32', '1/16', '1/8', '1/4', '1/2', '1/1', '2 bars', '4 bars', '8 bars'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap3Modifier,
    name: 'Tap3 modifier',
    unit: Unit.Choice,
    min: 0,
    max: 2,
    def: 1,
    taper: Taper.Stepped,
    steps: 3,
    choices: ['Straight', 'Dotted', 'Triplet'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap3Ratio,
    name: 'Tap3 ratio',
    unit: Unit.Choice,
    min: 0,
    max: 10,
    def: 0,
    taper: Taper.Stepped,
    steps: 11,
    choices: ['Auto', '×0.25', '×0.5', '×0.75', '×1', '×1.5', '×2', '×3', '×4', '×6', '×8'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap3Level,
    name: 'Tap3 level',
    unit: Unit.Decibels,
    min: -60,
    max: 6,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap3Pan,
    name: 'Tap3 pan',
    unit: Unit.Percent,
    min: -100,
    max: 100,
    def: -60,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap3Pitch,
    name: 'Tap3 pitch',
    unit: Unit.Semitones,
    min: -24,
    max: 24,
    def: 0,
    taper: Taper.Stepped,
    steps: 49,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap3Fine,
    name: 'Tap3 fine',
    unit: Unit.Cents,
    min: -50,
    max: 50,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap3Filter,
    name: 'Tap3 filter',
    unit: Unit.Choice,
    min: 0,
    max: 3,
    def: 0,
    taper: Taper.Stepped,
    steps: 4,
    choices: ['Off', 'LP', 'HP', 'BP'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap3Cutoff,
    name: 'Tap3 cutoff',
    unit: Unit.Hertz,
    min: 20,
    max: 20000,
    def: 20000,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap3Q,
    name: 'Tap3 Q',
    unit: Unit.Linear,
    min: 0.5,
    max: 8,
    def: 0.707,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap3Reverse,
    name: 'Tap3 reverse',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap3Mute,
    name: 'Tap3 mute',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap3Solo,
    name: 'Tap3 solo',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap4Time,
    name: 'Tap4 time',
    unit: Unit.Milliseconds,
    min: 1,
    max: 8000,
    def: 1000,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap4Division,
    name: 'Tap4 division',
    unit: Unit.Choice,
    min: 0,
    max: 9,
    def: 5,
    taper: Taper.Stepped,
    steps: 10,
    choices: ['1/64', '1/32', '1/16', '1/8', '1/4', '1/2', '1/1', '2 bars', '4 bars', '8 bars'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap4Modifier,
    name: 'Tap4 modifier',
    unit: Unit.Choice,
    min: 0,
    max: 2,
    def: 0,
    taper: Taper.Stepped,
    steps: 3,
    choices: ['Straight', 'Dotted', 'Triplet'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap4Ratio,
    name: 'Tap4 ratio',
    unit: Unit.Choice,
    min: 0,
    max: 10,
    def: 0,
    taper: Taper.Stepped,
    steps: 11,
    choices: ['Auto', '×0.25', '×0.5', '×0.75', '×1', '×1.5', '×2', '×3', '×4', '×6', '×8'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap4Level,
    name: 'Tap4 level',
    unit: Unit.Decibels,
    min: -60,
    max: 6,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap4Pan,
    name: 'Tap4 pan',
    unit: Unit.Percent,
    min: -100,
    max: 100,
    def: 60,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap4Pitch,
    name: 'Tap4 pitch',
    unit: Unit.Semitones,
    min: -24,
    max: 24,
    def: 0,
    taper: Taper.Stepped,
    steps: 49,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap4Fine,
    name: 'Tap4 fine',
    unit: Unit.Cents,
    min: -50,
    max: 50,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap4Filter,
    name: 'Tap4 filter',
    unit: Unit.Choice,
    min: 0,
    max: 3,
    def: 0,
    taper: Taper.Stepped,
    steps: 4,
    choices: ['Off', 'LP', 'HP', 'BP'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap4Cutoff,
    name: 'Tap4 cutoff',
    unit: Unit.Hertz,
    min: 20,
    max: 20000,
    def: 20000,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap4Q,
    name: 'Tap4 Q',
    unit: Unit.Linear,
    min: 0.5,
    max: 8,
    def: 0.707,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap4Reverse,
    name: 'Tap4 reverse',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap4Mute,
    name: 'Tap4 mute',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap4Solo,
    name: 'Tap4 solo',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap5Time,
    name: 'Tap5 time',
    unit: Unit.Milliseconds,
    min: 1,
    max: 8000,
    def: 1250,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap5Division,
    name: 'Tap5 division',
    unit: Unit.Choice,
    min: 0,
    max: 9,
    def: 5,
    taper: Taper.Stepped,
    steps: 10,
    choices: ['1/64', '1/32', '1/16', '1/8', '1/4', '1/2', '1/1', '2 bars', '4 bars', '8 bars'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap5Modifier,
    name: 'Tap5 modifier',
    unit: Unit.Choice,
    min: 0,
    max: 2,
    def: 1,
    taper: Taper.Stepped,
    steps: 3,
    choices: ['Straight', 'Dotted', 'Triplet'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap5Ratio,
    name: 'Tap5 ratio',
    unit: Unit.Choice,
    min: 0,
    max: 10,
    def: 0,
    taper: Taper.Stepped,
    steps: 11,
    choices: ['Auto', '×0.25', '×0.5', '×0.75', '×1', '×1.5', '×2', '×3', '×4', '×6', '×8'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap5Level,
    name: 'Tap5 level',
    unit: Unit.Decibels,
    min: -60,
    max: 6,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap5Pan,
    name: 'Tap5 pan',
    unit: Unit.Percent,
    min: -100,
    max: 100,
    def: -15,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap5Pitch,
    name: 'Tap5 pitch',
    unit: Unit.Semitones,
    min: -24,
    max: 24,
    def: 0,
    taper: Taper.Stepped,
    steps: 49,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap5Fine,
    name: 'Tap5 fine',
    unit: Unit.Cents,
    min: -50,
    max: 50,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap5Filter,
    name: 'Tap5 filter',
    unit: Unit.Choice,
    min: 0,
    max: 3,
    def: 0,
    taper: Taper.Stepped,
    steps: 4,
    choices: ['Off', 'LP', 'HP', 'BP'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap5Cutoff,
    name: 'Tap5 cutoff',
    unit: Unit.Hertz,
    min: 20,
    max: 20000,
    def: 20000,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap5Q,
    name: 'Tap5 Q',
    unit: Unit.Linear,
    min: 0.5,
    max: 8,
    def: 0.707,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap5Reverse,
    name: 'Tap5 reverse',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap5Mute,
    name: 'Tap5 mute',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap5Solo,
    name: 'Tap5 solo',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap6Time,
    name: 'Tap6 time',
    unit: Unit.Milliseconds,
    min: 1,
    max: 8000,
    def: 1500,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap6Division,
    name: 'Tap6 division',
    unit: Unit.Choice,
    min: 0,
    max: 9,
    def: 6,
    taper: Taper.Stepped,
    steps: 10,
    choices: ['1/64', '1/32', '1/16', '1/8', '1/4', '1/2', '1/1', '2 bars', '4 bars', '8 bars'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap6Modifier,
    name: 'Tap6 modifier',
    unit: Unit.Choice,
    min: 0,
    max: 2,
    def: 0,
    taper: Taper.Stepped,
    steps: 3,
    choices: ['Straight', 'Dotted', 'Triplet'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap6Ratio,
    name: 'Tap6 ratio',
    unit: Unit.Choice,
    min: 0,
    max: 10,
    def: 0,
    taper: Taper.Stepped,
    steps: 11,
    choices: ['Auto', '×0.25', '×0.5', '×0.75', '×1', '×1.5', '×2', '×3', '×4', '×6', '×8'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap6Level,
    name: 'Tap6 level',
    unit: Unit.Decibels,
    min: -60,
    max: 6,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap6Pan,
    name: 'Tap6 pan',
    unit: Unit.Percent,
    min: -100,
    max: 100,
    def: 15,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap6Pitch,
    name: 'Tap6 pitch',
    unit: Unit.Semitones,
    min: -24,
    max: 24,
    def: 0,
    taper: Taper.Stepped,
    steps: 49,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap6Fine,
    name: 'Tap6 fine',
    unit: Unit.Cents,
    min: -50,
    max: 50,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap6Filter,
    name: 'Tap6 filter',
    unit: Unit.Choice,
    min: 0,
    max: 3,
    def: 0,
    taper: Taper.Stepped,
    steps: 4,
    choices: ['Off', 'LP', 'HP', 'BP'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap6Cutoff,
    name: 'Tap6 cutoff',
    unit: Unit.Hertz,
    min: 20,
    max: 20000,
    def: 20000,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap6Q,
    name: 'Tap6 Q',
    unit: Unit.Linear,
    min: 0.5,
    max: 8,
    def: 0.707,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap6Reverse,
    name: 'Tap6 reverse',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap6Mute,
    name: 'Tap6 mute',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap6Solo,
    name: 'Tap6 solo',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap7Time,
    name: 'Tap7 time',
    unit: Unit.Milliseconds,
    min: 1,
    max: 8000,
    def: 1750,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap7Division,
    name: 'Tap7 division',
    unit: Unit.Choice,
    min: 0,
    max: 9,
    def: 6,
    taper: Taper.Stepped,
    steps: 10,
    choices: ['1/64', '1/32', '1/16', '1/8', '1/4', '1/2', '1/1', '2 bars', '4 bars', '8 bars'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap7Modifier,
    name: 'Tap7 modifier',
    unit: Unit.Choice,
    min: 0,
    max: 2,
    def: 1,
    taper: Taper.Stepped,
    steps: 3,
    choices: ['Straight', 'Dotted', 'Triplet'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap7Ratio,
    name: 'Tap7 ratio',
    unit: Unit.Choice,
    min: 0,
    max: 10,
    def: 0,
    taper: Taper.Stepped,
    steps: 11,
    choices: ['Auto', '×0.25', '×0.5', '×0.75', '×1', '×1.5', '×2', '×3', '×4', '×6', '×8'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap7Level,
    name: 'Tap7 level',
    unit: Unit.Decibels,
    min: -60,
    max: 6,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap7Pan,
    name: 'Tap7 pan',
    unit: Unit.Percent,
    min: -100,
    max: 100,
    def: -45,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap7Pitch,
    name: 'Tap7 pitch',
    unit: Unit.Semitones,
    min: -24,
    max: 24,
    def: 0,
    taper: Taper.Stepped,
    steps: 49,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap7Fine,
    name: 'Tap7 fine',
    unit: Unit.Cents,
    min: -50,
    max: 50,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap7Filter,
    name: 'Tap7 filter',
    unit: Unit.Choice,
    min: 0,
    max: 3,
    def: 0,
    taper: Taper.Stepped,
    steps: 4,
    choices: ['Off', 'LP', 'HP', 'BP'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap7Cutoff,
    name: 'Tap7 cutoff',
    unit: Unit.Hertz,
    min: 20,
    max: 20000,
    def: 20000,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap7Q,
    name: 'Tap7 Q',
    unit: Unit.Linear,
    min: 0.5,
    max: 8,
    def: 0.707,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap7Reverse,
    name: 'Tap7 reverse',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap7Mute,
    name: 'Tap7 mute',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap7Solo,
    name: 'Tap7 solo',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap8Time,
    name: 'Tap8 time',
    unit: Unit.Milliseconds,
    min: 1,
    max: 8000,
    def: 2000,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap8Division,
    name: 'Tap8 division',
    unit: Unit.Choice,
    min: 0,
    max: 9,
    def: 7,
    taper: Taper.Stepped,
    steps: 10,
    choices: ['1/64', '1/32', '1/16', '1/8', '1/4', '1/2', '1/1', '2 bars', '4 bars', '8 bars'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap8Modifier,
    name: 'Tap8 modifier',
    unit: Unit.Choice,
    min: 0,
    max: 2,
    def: 0,
    taper: Taper.Stepped,
    steps: 3,
    choices: ['Straight', 'Dotted', 'Triplet'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap8Ratio,
    name: 'Tap8 ratio',
    unit: Unit.Choice,
    min: 0,
    max: 10,
    def: 0,
    taper: Taper.Stepped,
    steps: 11,
    choices: ['Auto', '×0.25', '×0.5', '×0.75', '×1', '×1.5', '×2', '×3', '×4', '×6', '×8'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap8Level,
    name: 'Tap8 level',
    unit: Unit.Decibels,
    min: -60,
    max: 6,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap8Pan,
    name: 'Tap8 pan',
    unit: Unit.Percent,
    min: -100,
    max: 100,
    def: 45,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap8Pitch,
    name: 'Tap8 pitch',
    unit: Unit.Semitones,
    min: -24,
    max: 24,
    def: 0,
    taper: Taper.Stepped,
    steps: 49,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap8Fine,
    name: 'Tap8 fine',
    unit: Unit.Cents,
    min: -50,
    max: 50,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap8Filter,
    name: 'Tap8 filter',
    unit: Unit.Choice,
    min: 0,
    max: 3,
    def: 0,
    taper: Taper.Stepped,
    steps: 4,
    choices: ['Off', 'LP', 'HP', 'BP'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap8Cutoff,
    name: 'Tap8 cutoff',
    unit: Unit.Hertz,
    min: 20,
    max: 20000,
    def: 20000,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap8Q,
    name: 'Tap8 Q',
    unit: Unit.Linear,
    min: 0.5,
    max: 8,
    def: 0.707,
    taper: Taper.Logarithmic,
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap8Reverse,
    name: 'Tap8 reverse',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap8Mute,
    name: 'Tap8 mute',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularDelayParam.Tap8Solo,
    name: 'Tap8 solo',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
];

/**
 * What each parameter needs on the panel: which control, and what a screen
 * reader calls it. Not how it looks — colour and geometry are the face's, and
 * belong with the rest of the design language rather than in a generated file.
 *
 * `paramId` is a real id by construction. That is the half of D1 this file
 * exists to make unconstructible.
 */
export const granularDelayControls = [
  {
    id: 'mix',
    role: 'knob',
    paramId: GranularDelayParam.Mix,
    accessibleName: 'Wet/dry mix',
  },
  {
    id: 'topology',
    role: 'switch',
    paramId: GranularDelayParam.Topology,
    accessibleName: 'Feedback topology',
  },
  {
    id: 'cross',
    role: 'knob',
    paramId: GranularDelayParam.Cross,
    accessibleName: 'Cross-feedback amount',
  },
  {
    id: 'tap-count',
    role: 'switch',
    paramId: GranularDelayParam.TapCount,
    accessibleName: 'Number of taps',
  },
  {
    id: 'sync',
    role: 'toggle',
    paramId: GranularDelayParam.Sync,
    accessibleName: 'Tempo sync',
  },
  {
    id: 'time-mode',
    role: 'switch',
    paramId: GranularDelayParam.TimeMode,
    accessibleName: 'Absolute or relative tap times',
  },
  {
    id: 'spacing',
    role: 'switch',
    paramId: GranularDelayParam.Spacing,
    accessibleName: 'Head spacing preset',
  },
  {
    id: 'feedback',
    role: 'knob',
    paramId: GranularDelayParam.Feedback,
    accessibleName: 'Feedback amount',
  },
  {
    id: 'feedback-source',
    role: 'switch',
    paramId: GranularDelayParam.FeedbackSource,
    accessibleName: 'Feedback read source',
  },
  {
    id: 'feedback-time',
    role: 'knob',
    paramId: GranularDelayParam.FeedbackTime,
    accessibleName: 'Dedicated feedback time',
  },
  {
    id: 'feedback-division',
    role: 'switch',
    paramId: GranularDelayParam.FeedbackDivision,
    accessibleName: 'Feedback division',
  },
  {
    id: 'feedback-modifier',
    role: 'switch',
    paramId: GranularDelayParam.FeedbackModifier,
    accessibleName: 'Feedback division modifier',
  },
  {
    id: 'loop-lowpass',
    role: 'knob',
    paramId: GranularDelayParam.LoopLowpass,
    accessibleName: 'Loop lowpass corner',
  },
  {
    id: 'loop-highpass',
    role: 'knob',
    paramId: GranularDelayParam.LoopHighpass,
    accessibleName: 'Loop highpass corner',
  },
  {
    id: 'drive',
    role: 'knob',
    paramId: GranularDelayParam.Drive,
    accessibleName: 'Loop saturator drive',
  },
  {
    id: 'character',
    role: 'switch',
    paramId: GranularDelayParam.Character,
    accessibleName: 'Medium character',
  },
  {
    id: 'time-change',
    role: 'switch',
    paramId: GranularDelayParam.TimeChange,
    accessibleName: 'Delay-time change mode',
  },
  {
    id: 'smear',
    role: 'knob',
    paramId: GranularDelayParam.Smear,
    accessibleName: 'Granular smear',
  },
  {
    id: 'ducking',
    role: 'knob',
    paramId: GranularDelayParam.Ducking,
    accessibleName: 'Input-triggered ducking',
  },
  {
    id: 'width',
    role: 'knob',
    paramId: GranularDelayParam.Width,
    accessibleName: 'Wet stereo width',
  },
  {
    id: 'output-trim',
    role: 'knob',
    paramId: GranularDelayParam.OutputTrim,
    accessibleName: 'Output trim',
  },
  {
    id: 'quality',
    role: 'switch',
    paramId: GranularDelayParam.Quality,
    accessibleName: 'Quality tier',
  },
  {
    id: 'bypass',
    role: 'toggle',
    paramId: GranularDelayParam.Bypass,
    accessibleName: 'Bypass',
  },
  {
    id: 'wear',
    role: 'switch',
    paramId: GranularDelayParam.Wear,
    accessibleName: 'Transport wear',
  },
  {
    id: 'bias',
    role: 'knob',
    paramId: GranularDelayParam.Bias,
    accessibleName: 'Tape bias',
  },
  {
    id: 'age',
    role: 'knob',
    paramId: GranularDelayParam.Age,
    accessibleName: 'Tape age',
  },
  {
    id: 'stages',
    role: 'switch',
    paramId: GranularDelayParam.Stages,
    accessibleName: 'BBD stage count',
  },
  {
    id: 'clock-whine',
    role: 'toggle',
    paramId: GranularDelayParam.ClockWhine,
    accessibleName: 'BBD clock feedthrough',
  },
  {
    id: 'tap1-time',
    role: 'knob',
    paramId: GranularDelayParam.Tap1Time,
    accessibleName: 'Tap 1 time',
  },
  {
    id: 'tap1-division',
    role: 'switch',
    paramId: GranularDelayParam.Tap1Division,
    accessibleName: 'Tap 1 division',
  },
  {
    id: 'tap1-modifier',
    role: 'switch',
    paramId: GranularDelayParam.Tap1Modifier,
    accessibleName: 'Tap 1 division modifier',
  },
  {
    id: 'tap1-level',
    role: 'knob',
    paramId: GranularDelayParam.Tap1Level,
    accessibleName: 'Tap 1 level',
  },
  {
    id: 'tap1-pan',
    role: 'knob',
    paramId: GranularDelayParam.Tap1Pan,
    accessibleName: 'Tap 1 pan',
  },
  {
    id: 'tap1-pitch',
    role: 'knob',
    paramId: GranularDelayParam.Tap1Pitch,
    accessibleName: 'Tap 1 pitch',
  },
  {
    id: 'tap1-fine',
    role: 'knob',
    paramId: GranularDelayParam.Tap1Fine,
    accessibleName: 'Tap 1 fine tune',
  },
  {
    id: 'tap1-filter',
    role: 'switch',
    paramId: GranularDelayParam.Tap1Filter,
    accessibleName: 'Tap 1 filter type',
  },
  {
    id: 'tap1-cutoff',
    role: 'knob',
    paramId: GranularDelayParam.Tap1Cutoff,
    accessibleName: 'Tap 1 filter cutoff',
  },
  {
    id: 'tap1-q',
    role: 'knob',
    paramId: GranularDelayParam.Tap1Q,
    accessibleName: 'Tap 1 filter resonance',
  },
  {
    id: 'tap1-reverse',
    role: 'toggle',
    paramId: GranularDelayParam.Tap1Reverse,
    accessibleName: 'Tap 1 reverse',
  },
  {
    id: 'tap1-mute',
    role: 'toggle',
    paramId: GranularDelayParam.Tap1Mute,
    accessibleName: 'Tap 1 mute',
  },
  {
    id: 'tap1-solo',
    role: 'toggle',
    paramId: GranularDelayParam.Tap1Solo,
    accessibleName: 'Tap 1 solo',
  },
  {
    id: 'tap2-time',
    role: 'knob',
    paramId: GranularDelayParam.Tap2Time,
    accessibleName: 'Tap 2 time',
  },
  {
    id: 'tap2-division',
    role: 'switch',
    paramId: GranularDelayParam.Tap2Division,
    accessibleName: 'Tap 2 division',
  },
  {
    id: 'tap2-modifier',
    role: 'switch',
    paramId: GranularDelayParam.Tap2Modifier,
    accessibleName: 'Tap 2 division modifier',
  },
  {
    id: 'tap2-ratio',
    role: 'switch',
    paramId: GranularDelayParam.Tap2Ratio,
    accessibleName: 'Tap 2 ratio in relative mode',
  },
  {
    id: 'tap2-level',
    role: 'knob',
    paramId: GranularDelayParam.Tap2Level,
    accessibleName: 'Tap 2 level',
  },
  {
    id: 'tap2-pan',
    role: 'knob',
    paramId: GranularDelayParam.Tap2Pan,
    accessibleName: 'Tap 2 pan',
  },
  {
    id: 'tap2-pitch',
    role: 'knob',
    paramId: GranularDelayParam.Tap2Pitch,
    accessibleName: 'Tap 2 pitch',
  },
  {
    id: 'tap2-fine',
    role: 'knob',
    paramId: GranularDelayParam.Tap2Fine,
    accessibleName: 'Tap 2 fine tune',
  },
  {
    id: 'tap2-filter',
    role: 'switch',
    paramId: GranularDelayParam.Tap2Filter,
    accessibleName: 'Tap 2 filter type',
  },
  {
    id: 'tap2-cutoff',
    role: 'knob',
    paramId: GranularDelayParam.Tap2Cutoff,
    accessibleName: 'Tap 2 filter cutoff',
  },
  {
    id: 'tap2-q',
    role: 'knob',
    paramId: GranularDelayParam.Tap2Q,
    accessibleName: 'Tap 2 filter resonance',
  },
  {
    id: 'tap2-reverse',
    role: 'toggle',
    paramId: GranularDelayParam.Tap2Reverse,
    accessibleName: 'Tap 2 reverse',
  },
  {
    id: 'tap2-mute',
    role: 'toggle',
    paramId: GranularDelayParam.Tap2Mute,
    accessibleName: 'Tap 2 mute',
  },
  {
    id: 'tap2-solo',
    role: 'toggle',
    paramId: GranularDelayParam.Tap2Solo,
    accessibleName: 'Tap 2 solo',
  },
  {
    id: 'tap3-time',
    role: 'knob',
    paramId: GranularDelayParam.Tap3Time,
    accessibleName: 'Tap 3 time',
  },
  {
    id: 'tap3-division',
    role: 'switch',
    paramId: GranularDelayParam.Tap3Division,
    accessibleName: 'Tap 3 division',
  },
  {
    id: 'tap3-modifier',
    role: 'switch',
    paramId: GranularDelayParam.Tap3Modifier,
    accessibleName: 'Tap 3 division modifier',
  },
  {
    id: 'tap3-ratio',
    role: 'switch',
    paramId: GranularDelayParam.Tap3Ratio,
    accessibleName: 'Tap 3 ratio in relative mode',
  },
  {
    id: 'tap3-level',
    role: 'knob',
    paramId: GranularDelayParam.Tap3Level,
    accessibleName: 'Tap 3 level',
  },
  {
    id: 'tap3-pan',
    role: 'knob',
    paramId: GranularDelayParam.Tap3Pan,
    accessibleName: 'Tap 3 pan',
  },
  {
    id: 'tap3-pitch',
    role: 'knob',
    paramId: GranularDelayParam.Tap3Pitch,
    accessibleName: 'Tap 3 pitch',
  },
  {
    id: 'tap3-fine',
    role: 'knob',
    paramId: GranularDelayParam.Tap3Fine,
    accessibleName: 'Tap 3 fine tune',
  },
  {
    id: 'tap3-filter',
    role: 'switch',
    paramId: GranularDelayParam.Tap3Filter,
    accessibleName: 'Tap 3 filter type',
  },
  {
    id: 'tap3-cutoff',
    role: 'knob',
    paramId: GranularDelayParam.Tap3Cutoff,
    accessibleName: 'Tap 3 filter cutoff',
  },
  {
    id: 'tap3-q',
    role: 'knob',
    paramId: GranularDelayParam.Tap3Q,
    accessibleName: 'Tap 3 filter resonance',
  },
  {
    id: 'tap3-reverse',
    role: 'toggle',
    paramId: GranularDelayParam.Tap3Reverse,
    accessibleName: 'Tap 3 reverse',
  },
  {
    id: 'tap3-mute',
    role: 'toggle',
    paramId: GranularDelayParam.Tap3Mute,
    accessibleName: 'Tap 3 mute',
  },
  {
    id: 'tap3-solo',
    role: 'toggle',
    paramId: GranularDelayParam.Tap3Solo,
    accessibleName: 'Tap 3 solo',
  },
  {
    id: 'tap4-time',
    role: 'knob',
    paramId: GranularDelayParam.Tap4Time,
    accessibleName: 'Tap 4 time',
  },
  {
    id: 'tap4-division',
    role: 'switch',
    paramId: GranularDelayParam.Tap4Division,
    accessibleName: 'Tap 4 division',
  },
  {
    id: 'tap4-modifier',
    role: 'switch',
    paramId: GranularDelayParam.Tap4Modifier,
    accessibleName: 'Tap 4 division modifier',
  },
  {
    id: 'tap4-ratio',
    role: 'switch',
    paramId: GranularDelayParam.Tap4Ratio,
    accessibleName: 'Tap 4 ratio in relative mode',
  },
  {
    id: 'tap4-level',
    role: 'knob',
    paramId: GranularDelayParam.Tap4Level,
    accessibleName: 'Tap 4 level',
  },
  {
    id: 'tap4-pan',
    role: 'knob',
    paramId: GranularDelayParam.Tap4Pan,
    accessibleName: 'Tap 4 pan',
  },
  {
    id: 'tap4-pitch',
    role: 'knob',
    paramId: GranularDelayParam.Tap4Pitch,
    accessibleName: 'Tap 4 pitch',
  },
  {
    id: 'tap4-fine',
    role: 'knob',
    paramId: GranularDelayParam.Tap4Fine,
    accessibleName: 'Tap 4 fine tune',
  },
  {
    id: 'tap4-filter',
    role: 'switch',
    paramId: GranularDelayParam.Tap4Filter,
    accessibleName: 'Tap 4 filter type',
  },
  {
    id: 'tap4-cutoff',
    role: 'knob',
    paramId: GranularDelayParam.Tap4Cutoff,
    accessibleName: 'Tap 4 filter cutoff',
  },
  {
    id: 'tap4-q',
    role: 'knob',
    paramId: GranularDelayParam.Tap4Q,
    accessibleName: 'Tap 4 filter resonance',
  },
  {
    id: 'tap4-reverse',
    role: 'toggle',
    paramId: GranularDelayParam.Tap4Reverse,
    accessibleName: 'Tap 4 reverse',
  },
  {
    id: 'tap4-mute',
    role: 'toggle',
    paramId: GranularDelayParam.Tap4Mute,
    accessibleName: 'Tap 4 mute',
  },
  {
    id: 'tap4-solo',
    role: 'toggle',
    paramId: GranularDelayParam.Tap4Solo,
    accessibleName: 'Tap 4 solo',
  },
  {
    id: 'tap5-time',
    role: 'knob',
    paramId: GranularDelayParam.Tap5Time,
    accessibleName: 'Tap 5 time',
  },
  {
    id: 'tap5-division',
    role: 'switch',
    paramId: GranularDelayParam.Tap5Division,
    accessibleName: 'Tap 5 division',
  },
  {
    id: 'tap5-modifier',
    role: 'switch',
    paramId: GranularDelayParam.Tap5Modifier,
    accessibleName: 'Tap 5 division modifier',
  },
  {
    id: 'tap5-ratio',
    role: 'switch',
    paramId: GranularDelayParam.Tap5Ratio,
    accessibleName: 'Tap 5 ratio in relative mode',
  },
  {
    id: 'tap5-level',
    role: 'knob',
    paramId: GranularDelayParam.Tap5Level,
    accessibleName: 'Tap 5 level',
  },
  {
    id: 'tap5-pan',
    role: 'knob',
    paramId: GranularDelayParam.Tap5Pan,
    accessibleName: 'Tap 5 pan',
  },
  {
    id: 'tap5-pitch',
    role: 'knob',
    paramId: GranularDelayParam.Tap5Pitch,
    accessibleName: 'Tap 5 pitch',
  },
  {
    id: 'tap5-fine',
    role: 'knob',
    paramId: GranularDelayParam.Tap5Fine,
    accessibleName: 'Tap 5 fine tune',
  },
  {
    id: 'tap5-filter',
    role: 'switch',
    paramId: GranularDelayParam.Tap5Filter,
    accessibleName: 'Tap 5 filter type',
  },
  {
    id: 'tap5-cutoff',
    role: 'knob',
    paramId: GranularDelayParam.Tap5Cutoff,
    accessibleName: 'Tap 5 filter cutoff',
  },
  {
    id: 'tap5-q',
    role: 'knob',
    paramId: GranularDelayParam.Tap5Q,
    accessibleName: 'Tap 5 filter resonance',
  },
  {
    id: 'tap5-reverse',
    role: 'toggle',
    paramId: GranularDelayParam.Tap5Reverse,
    accessibleName: 'Tap 5 reverse',
  },
  {
    id: 'tap5-mute',
    role: 'toggle',
    paramId: GranularDelayParam.Tap5Mute,
    accessibleName: 'Tap 5 mute',
  },
  {
    id: 'tap5-solo',
    role: 'toggle',
    paramId: GranularDelayParam.Tap5Solo,
    accessibleName: 'Tap 5 solo',
  },
  {
    id: 'tap6-time',
    role: 'knob',
    paramId: GranularDelayParam.Tap6Time,
    accessibleName: 'Tap 6 time',
  },
  {
    id: 'tap6-division',
    role: 'switch',
    paramId: GranularDelayParam.Tap6Division,
    accessibleName: 'Tap 6 division',
  },
  {
    id: 'tap6-modifier',
    role: 'switch',
    paramId: GranularDelayParam.Tap6Modifier,
    accessibleName: 'Tap 6 division modifier',
  },
  {
    id: 'tap6-ratio',
    role: 'switch',
    paramId: GranularDelayParam.Tap6Ratio,
    accessibleName: 'Tap 6 ratio in relative mode',
  },
  {
    id: 'tap6-level',
    role: 'knob',
    paramId: GranularDelayParam.Tap6Level,
    accessibleName: 'Tap 6 level',
  },
  {
    id: 'tap6-pan',
    role: 'knob',
    paramId: GranularDelayParam.Tap6Pan,
    accessibleName: 'Tap 6 pan',
  },
  {
    id: 'tap6-pitch',
    role: 'knob',
    paramId: GranularDelayParam.Tap6Pitch,
    accessibleName: 'Tap 6 pitch',
  },
  {
    id: 'tap6-fine',
    role: 'knob',
    paramId: GranularDelayParam.Tap6Fine,
    accessibleName: 'Tap 6 fine tune',
  },
  {
    id: 'tap6-filter',
    role: 'switch',
    paramId: GranularDelayParam.Tap6Filter,
    accessibleName: 'Tap 6 filter type',
  },
  {
    id: 'tap6-cutoff',
    role: 'knob',
    paramId: GranularDelayParam.Tap6Cutoff,
    accessibleName: 'Tap 6 filter cutoff',
  },
  {
    id: 'tap6-q',
    role: 'knob',
    paramId: GranularDelayParam.Tap6Q,
    accessibleName: 'Tap 6 filter resonance',
  },
  {
    id: 'tap6-reverse',
    role: 'toggle',
    paramId: GranularDelayParam.Tap6Reverse,
    accessibleName: 'Tap 6 reverse',
  },
  {
    id: 'tap6-mute',
    role: 'toggle',
    paramId: GranularDelayParam.Tap6Mute,
    accessibleName: 'Tap 6 mute',
  },
  {
    id: 'tap6-solo',
    role: 'toggle',
    paramId: GranularDelayParam.Tap6Solo,
    accessibleName: 'Tap 6 solo',
  },
  {
    id: 'tap7-time',
    role: 'knob',
    paramId: GranularDelayParam.Tap7Time,
    accessibleName: 'Tap 7 time',
  },
  {
    id: 'tap7-division',
    role: 'switch',
    paramId: GranularDelayParam.Tap7Division,
    accessibleName: 'Tap 7 division',
  },
  {
    id: 'tap7-modifier',
    role: 'switch',
    paramId: GranularDelayParam.Tap7Modifier,
    accessibleName: 'Tap 7 division modifier',
  },
  {
    id: 'tap7-ratio',
    role: 'switch',
    paramId: GranularDelayParam.Tap7Ratio,
    accessibleName: 'Tap 7 ratio in relative mode',
  },
  {
    id: 'tap7-level',
    role: 'knob',
    paramId: GranularDelayParam.Tap7Level,
    accessibleName: 'Tap 7 level',
  },
  {
    id: 'tap7-pan',
    role: 'knob',
    paramId: GranularDelayParam.Tap7Pan,
    accessibleName: 'Tap 7 pan',
  },
  {
    id: 'tap7-pitch',
    role: 'knob',
    paramId: GranularDelayParam.Tap7Pitch,
    accessibleName: 'Tap 7 pitch',
  },
  {
    id: 'tap7-fine',
    role: 'knob',
    paramId: GranularDelayParam.Tap7Fine,
    accessibleName: 'Tap 7 fine tune',
  },
  {
    id: 'tap7-filter',
    role: 'switch',
    paramId: GranularDelayParam.Tap7Filter,
    accessibleName: 'Tap 7 filter type',
  },
  {
    id: 'tap7-cutoff',
    role: 'knob',
    paramId: GranularDelayParam.Tap7Cutoff,
    accessibleName: 'Tap 7 filter cutoff',
  },
  {
    id: 'tap7-q',
    role: 'knob',
    paramId: GranularDelayParam.Tap7Q,
    accessibleName: 'Tap 7 filter resonance',
  },
  {
    id: 'tap7-reverse',
    role: 'toggle',
    paramId: GranularDelayParam.Tap7Reverse,
    accessibleName: 'Tap 7 reverse',
  },
  {
    id: 'tap7-mute',
    role: 'toggle',
    paramId: GranularDelayParam.Tap7Mute,
    accessibleName: 'Tap 7 mute',
  },
  {
    id: 'tap7-solo',
    role: 'toggle',
    paramId: GranularDelayParam.Tap7Solo,
    accessibleName: 'Tap 7 solo',
  },
  {
    id: 'tap8-time',
    role: 'knob',
    paramId: GranularDelayParam.Tap8Time,
    accessibleName: 'Tap 8 time',
  },
  {
    id: 'tap8-division',
    role: 'switch',
    paramId: GranularDelayParam.Tap8Division,
    accessibleName: 'Tap 8 division',
  },
  {
    id: 'tap8-modifier',
    role: 'switch',
    paramId: GranularDelayParam.Tap8Modifier,
    accessibleName: 'Tap 8 division modifier',
  },
  {
    id: 'tap8-ratio',
    role: 'switch',
    paramId: GranularDelayParam.Tap8Ratio,
    accessibleName: 'Tap 8 ratio in relative mode',
  },
  {
    id: 'tap8-level',
    role: 'knob',
    paramId: GranularDelayParam.Tap8Level,
    accessibleName: 'Tap 8 level',
  },
  {
    id: 'tap8-pan',
    role: 'knob',
    paramId: GranularDelayParam.Tap8Pan,
    accessibleName: 'Tap 8 pan',
  },
  {
    id: 'tap8-pitch',
    role: 'knob',
    paramId: GranularDelayParam.Tap8Pitch,
    accessibleName: 'Tap 8 pitch',
  },
  {
    id: 'tap8-fine',
    role: 'knob',
    paramId: GranularDelayParam.Tap8Fine,
    accessibleName: 'Tap 8 fine tune',
  },
  {
    id: 'tap8-filter',
    role: 'switch',
    paramId: GranularDelayParam.Tap8Filter,
    accessibleName: 'Tap 8 filter type',
  },
  {
    id: 'tap8-cutoff',
    role: 'knob',
    paramId: GranularDelayParam.Tap8Cutoff,
    accessibleName: 'Tap 8 filter cutoff',
  },
  {
    id: 'tap8-q',
    role: 'knob',
    paramId: GranularDelayParam.Tap8Q,
    accessibleName: 'Tap 8 filter resonance',
  },
  {
    id: 'tap8-reverse',
    role: 'toggle',
    paramId: GranularDelayParam.Tap8Reverse,
    accessibleName: 'Tap 8 reverse',
  },
  {
    id: 'tap8-mute',
    role: 'toggle',
    paramId: GranularDelayParam.Tap8Mute,
    accessibleName: 'Tap 8 mute',
  },
  {
    id: 'tap8-solo',
    role: 'toggle',
    paramId: GranularDelayParam.Tap8Solo,
    accessibleName: 'Tap 8 solo',
  },
] as const;
