// GENERATED FILE — do not edit.
//
// Written by scripts/generate-params.mjs from motionwave/manifests/fx-02-granular-reverb.json.
// Edit the manifest and re-run `npm run params`. A hand edit here is exactly
// the second opinion the manifest exists to prevent, and `npm run params:check`
// fails the build if one is present.
import { defineParam } from '../../param/spec';
import type { ParamSpec } from '../../param/spec';
import { Taper, Unit } from '../../param/units';

/** Parameter ids, the same numbers the C++ enum carries. */
export const GranularReverbParam = {
  Mix: 1,
  PreDelay: 2,
  Size: 3,
  MinOffset: 4,
  Decay: 5,
  Freeze: 6,
  GrainSize: 7,
  Density: 8,
  Spray: 9,
  OnsetJitter: 10,
  LengthJitter: 11,
  AmpJitter: 12,
  WindowShape: 13,
  PitchSet: 14,
  PitchSpread: 15,
  Diffusion: 16,
  Damping: 17,
  Tilt: 18,
  Width: 19,
  OutputTrim: 20,
  Quality: 21,
  Bypass: 22,
  PreDelaySync: 23,
} as const;

export type GranularReverbParamId = (typeof GranularReverbParam)[keyof typeof GranularReverbParam];

/**
 * Every range, default and taper, straight from the manifest — which took them
 * from the Reference Spec Sheet. A control that sweeps a different range than
 * its sheet fails the unit's acceptance test on a number nobody checks by ear.
 */
export const granularReverbSpecs: readonly ParamSpec[] = [
  defineParam({
    id: GranularReverbParam.Mix,
    name: 'Mix',
    unit: Unit.Percent,
    min: 0,
    max: 100,
    def: 35,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularReverbParam.PreDelay,
    name: 'Pre-delay',
    unit: Unit.Milliseconds,
    min: 0,
    max: 500,
    def: 20,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularReverbParam.Size,
    name: 'Size',
    unit: Unit.Milliseconds,
    min: 20,
    max: 4000,
    def: 800,
    taper: Taper.Logarithmic,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularReverbParam.MinOffset,
    name: 'Min offset',
    unit: Unit.Milliseconds,
    min: 5,
    max: 500,
    def: 20,
    taper: Taper.Logarithmic,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularReverbParam.Decay,
    name: 'Decay',
    unit: Unit.Seconds,
    min: 0.1,
    max: 60,
    def: 3,
    taper: Taper.Logarithmic,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularReverbParam.Freeze,
    name: 'Freeze',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularReverbParam.GrainSize,
    name: 'Grain size',
    unit: Unit.Milliseconds,
    min: 5,
    max: 500,
    def: 60,
    taper: Taper.Logarithmic,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularReverbParam.Density,
    name: 'Density',
    unit: Unit.Hertz,
    min: 1,
    max: 2000,
    def: 350,
    taper: Taper.Logarithmic,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularReverbParam.Spray,
    name: 'Spray',
    unit: Unit.Percent,
    min: 0,
    max: 100,
    def: 70,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularReverbParam.OnsetJitter,
    name: 'Onset jitter',
    unit: Unit.Percent,
    min: 0,
    max: 100,
    def: 60,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularReverbParam.LengthJitter,
    name: 'Length jitter',
    unit: Unit.Percent,
    min: 0,
    max: 100,
    def: 25,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularReverbParam.AmpJitter,
    name: 'Amp jitter',
    unit: Unit.Percent,
    min: 0,
    max: 100,
    def: 15,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularReverbParam.WindowShape,
    name: 'Window shape',
    unit: Unit.Percent,
    min: 0,
    max: 100,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularReverbParam.PitchSet,
    name: 'Pitch set',
    unit: Unit.Choice,
    min: 0,
    max: 7,
    def: 0,
    taper: Taper.Stepped,
    steps: 8,
    choices: ['Unison', 'Octave up', 'Octave down', 'Fifth', 'Major', 'Minor', 'Sus', 'Wide'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularReverbParam.PitchSpread,
    name: 'Pitch spread',
    unit: Unit.Cents,
    min: 0,
    max: 100,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularReverbParam.Diffusion,
    name: 'Diffusion',
    unit: Unit.Percent,
    min: 0,
    max: 100,
    def: 60,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularReverbParam.Damping,
    name: 'Damping',
    unit: Unit.Percent,
    min: 0,
    max: 100,
    def: 45,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularReverbParam.Tilt,
    name: 'Tilt',
    unit: Unit.Decibels,
    min: -12,
    max: 12,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularReverbParam.Width,
    name: 'Width',
    unit: Unit.Percent,
    min: 0,
    max: 200,
    def: 100,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularReverbParam.OutputTrim,
    name: 'Output trim',
    unit: Unit.Decibels,
    min: -24,
    max: 24,
    def: 0,
    taper: Taper.Linear,
    smoothingMs: 20,
  }),
  defineParam({
    id: GranularReverbParam.Quality,
    name: 'Quality',
    unit: Unit.Choice,
    min: 0,
    max: 2,
    def: 1,
    taper: Taper.Stepped,
    steps: 3,
    choices: ['Eco', 'Studio', 'Max'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularReverbParam.Bypass,
    name: 'Bypass',
    unit: Unit.Choice,
    min: 0,
    max: 1,
    def: 0,
    taper: Taper.Stepped,
    steps: 2,
    choices: ['Off', 'On'],
    smoothingMs: 0,
  }),
  defineParam({
    id: GranularReverbParam.PreDelaySync,
    name: 'Pre-delay sync',
    unit: Unit.Choice,
    min: 0,
    max: 4,
    def: 0,
    taper: Taper.Stepped,
    steps: 9,
    choices: ['Off', '1/32', '1/16', '1/8 T', '1/8', '1/4 T', '1/4', '1/2', '1 bar'],
    smoothingMs: 0,
  }),
];

/**
 * What each parameter needs on the panel: which control, and what a screen
 * reader calls it. Not how it looks — colour and geometry are the face's, and
 * belong with the rest of the design language rather than in a generated file.
 *
 * `paramId` is a real id by construction. That is the half of D1 this file
 * exists to make unconstructible.
 */
export const granularReverbControls = [
  {
    id: 'mix',
    role: 'knob',
    paramId: GranularReverbParam.Mix,
    accessibleName: 'Wet/dry mix',
  },
  {
    id: 'pre-delay',
    role: 'knob',
    paramId: GranularReverbParam.PreDelay,
    accessibleName: 'Pre-delay',
  },
  {
    id: 'size',
    role: 'knob',
    paramId: GranularReverbParam.Size,
    accessibleName: 'Read window size',
  },
  {
    id: 'min-offset',
    role: 'knob',
    paramId: GranularReverbParam.MinOffset,
    accessibleName: 'Minimum read offset',
  },
  {
    id: 'decay',
    role: 'knob',
    paramId: GranularReverbParam.Decay,
    accessibleName: 'Decay time',
  },
  {
    id: 'freeze',
    role: 'toggle',
    paramId: GranularReverbParam.Freeze,
    accessibleName: 'Freeze',
  },
  {
    id: 'grain-size',
    role: 'knob',
    paramId: GranularReverbParam.GrainSize,
    accessibleName: 'Grain size',
  },
  {
    id: 'density',
    role: 'knob',
    paramId: GranularReverbParam.Density,
    accessibleName: 'Grain density',
  },
  {
    id: 'spray',
    role: 'knob',
    paramId: GranularReverbParam.Spray,
    accessibleName: 'Position spray',
  },
  {
    id: 'onset-jitter',
    role: 'knob',
    paramId: GranularReverbParam.OnsetJitter,
    accessibleName: 'Onset jitter',
  },
  {
    id: 'length-jitter',
    role: 'knob',
    paramId: GranularReverbParam.LengthJitter,
    accessibleName: 'Length jitter',
  },
  {
    id: 'amp-jitter',
    role: 'knob',
    paramId: GranularReverbParam.AmpJitter,
    accessibleName: 'Amplitude jitter',
  },
  {
    id: 'window-shape',
    role: 'knob',
    paramId: GranularReverbParam.WindowShape,
    accessibleName: 'Grain window shape',
  },
  {
    id: 'pitch-set',
    role: 'switch',
    paramId: GranularReverbParam.PitchSet,
    accessibleName: 'Shimmer pitch set',
  },
  {
    id: 'pitch-spread',
    role: 'knob',
    paramId: GranularReverbParam.PitchSpread,
    accessibleName: 'Pitch spread',
  },
  {
    id: 'diffusion',
    role: 'knob',
    paramId: GranularReverbParam.Diffusion,
    accessibleName: 'Diffusion',
  },
  {
    id: 'damping',
    role: 'knob',
    paramId: GranularReverbParam.Damping,
    accessibleName: 'High-frequency damping',
  },
  {
    id: 'tilt',
    role: 'knob',
    paramId: GranularReverbParam.Tilt,
    accessibleName: 'Feedback tilt',
  },
  {
    id: 'width',
    role: 'knob',
    paramId: GranularReverbParam.Width,
    accessibleName: 'Stereo width',
  },
  {
    id: 'output-trim',
    role: 'knob',
    paramId: GranularReverbParam.OutputTrim,
    accessibleName: 'Output trim',
  },
  {
    id: 'quality',
    role: 'switch',
    paramId: GranularReverbParam.Quality,
    accessibleName: 'Quality tier',
  },
  {
    id: 'bypass',
    role: 'toggle',
    paramId: GranularReverbParam.Bypass,
    accessibleName: 'Bypass',
  },
  {
    id: 'pre-delay-sync',
    role: 'knob',
    paramId: GranularReverbParam.PreDelaySync,
    accessibleName: 'Pre-delay tempo sync',
  },
] as const;
