#!/usr/bin/env node
// docs-guard — no tracked document records product state unless something
// checks it.
//
// Three documents have gone stale in three directives: `SOAK.md` carried a
// FAIL the product had fixed, the parity documents marked five closed items
// MISSING, and the RA backlog held three tickets that had been closed. The
// cause is the same each time and it is not carelessness: a document that
// records state and is not verified *will* be wrong, and its being wrong is
// invisible. Nothing about reading it tells you.
//
// So every file under `docs/` is GENERATED, GUARDED or NARRATIVE, and each of
// the three means something enforceable here:
//
//   GENERATED  declares the script that writes it, and — where it names the
//              artefact it describes — is compared against that artefact now.
//   GUARDED    names the guard, which must exist and must run in the build.
//   NARRATIVE  contains no record of this product's state, in any of the
//              shapes state takes. That is what makes the class a promise
//              rather than a label.
//
// Unclassified fails. A registry entry for a file that is gone fails. Both are
// the same rule from opposite ends: the classification is checked against the
// tree rather than trusted, because a registry that goes stale is the exact
// failure this exists to stop, one level up.
import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, relative, sep } from 'node:path';
import { DOCS } from './docs/registry.mjs';
import { stateRecords, PATTERNS } from './docs/state.mjs';

const ROOT = process.cwd();
const DOCS_DIR = join(ROOT, 'docs');
const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
/** Release mode: a stale generated report is a failure rather than a note. */
const STRICT = process.argv.includes('--strict');

const problems = [];
const notes = [];
const fail = (file, msg) => problems.push(`${file}: ${msg}`);

/** Every tracked document, as repo-relative POSIX paths. */
function sweep(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...sweep(full));
    else if (/\.(md|json|txt)$/.test(name)) out.push(relative(ROOT, full).split(sep).join('/'));
  }
  return out;
}

const files = sweep(DOCS_DIR).sort();

// ── 1. Everything is classified, and every classification names a file ──────
for (const f of files) {
  if (!DOCS[f]) {
    fail(
      f,
      'is not classified. Add it to `scripts/docs/registry.mjs` as GENERATED (a script writes ' +
        'it), GUARDED (a build guard checks its claims) or NARRATIVE (it records reasoning, ' +
        'never state).',
    );
  }
}
for (const f of Object.keys(DOCS)) {
  if (!files.includes(f)) fail(f, 'is in the registry and not in the tree.');
}

// ── 2. GENERATED: the header is true, and the currency is checked ───────────
/**
 * The entry bundle this build produced, for documents that name one.
 *
 * Read out of `index.html` rather than by picking the first `index-*.js` in
 * `dist/assets`. There is more than one — a lazy chunk carries the same prefix
 * — and directory order is not entry order, so the first version of this named
 * the wrong file in its own failure message. `soak.mjs` reads the same line to
 * decide what it is measuring, which is what makes the two comparable.
 */
function currentBundle() {
  const indexPath = join(ROOT, 'dist/index.html');
  if (!existsSync(indexPath)) return null;
  return /assets\/(index-[\w-]+\.js)/.exec(readFileSync(indexPath, 'utf8'))?.[1] ?? null;
}

for (const [f, spec] of Object.entries(DOCS)) {
  if (spec.kind !== 'GENERATED' || !files.includes(f)) continue;
  const text = readFileSync(join(ROOT, f), 'utf8');

  if (!pkg.scripts[spec.by]) {
    fail(f, `is generated by \`npm run ${spec.by}\`, and package.json has no such script.`);
  }

  // JSON has nowhere to put a header sentence; the markdown beside it carries
  // the claim, and this checks the markdown.
  if (f.endsWith('.md')) {
    const header = text.split('\n').slice(0, 6).join('\n');
    if (!header.includes(`npm run ${spec.by}`) || !/Do not edit by hand/i.test(header)) {
      fail(
        f,
        `is GENERATED but its first lines do not say so. They must read ` +
          `"Generated by \`npm run ${spec.by}\`. Do not edit by hand." — a generated file ` +
          `that does not announce it gets edited.`,
      );
    }
  }

  if (spec.declares === 'bundle') {
    const named = /`(index-[A-Za-z0-9_-]+\.js)`/.exec(text)?.[1] ?? null;
    const now = currentBundle();
    if (!named) {
      fail(f, 'declares a bundle and no `index-*.js` name could be found in it.');
    } else if (!now) {
      // Skipping is not a pass, and it says so rather than staying quiet.
      notes.push(
        `${f}: SKIPPED the currency check — there is no dist/ to compare against. ` +
          `Run \`npm run build\` first. This is not a pass.`,
      );
    } else if (named !== now) {
      /*
       * A failure at release, a note in the build, and the reason is ordering
       * rather than severity.
       *
       * `vite.config.ts` compiles the commit date into the bundle, so every
       * commit produces a new hash — including the commit that lands a fresh
       * soak report. Made a hard build failure, this could never be satisfied:
       * re-running the soak changes SOAK.md, which changes the commit, which
       * changes the hash the report has just been made to name. So the build
       * says it loudly and `--strict` refuses, and `--strict` is what the
       * release sequence runs against the artefact it is about to deploy.
       * `scripts/check-checks.mjs` declares it, so it is not a side door.
       */
      const msg =
        `describes bundle \`${named}\` and dist/ now holds \`${now}\`. This is the SOAK.md ` +
        `failure exactly: the file says in as many words that a different hash means it ` +
        `describes a product that has moved, and nothing read that line. Re-run ` +
        `\`npm run ${spec.by}\` before deploying.`;
      if (STRICT) fail(f, msg);
      else notes.push(`${f}: STALE — ${msg}`);
    }
  }
}

// ── 3. GUARDED: the guard exists and runs where it is claimed to ───────────
for (const [f, spec] of Object.entries(DOCS)) {
  if (spec.kind !== 'GUARDED' || !files.includes(f)) continue;
  if (!pkg.scripts[spec.by]) {
    fail(f, `names guard \`${spec.by}\`, and package.json has no such script.`);
    continue;
  }
  if (!pkg.scripts.build.includes(`${spec.by}.mjs`)) {
    fail(
      f,
      `is GUARDED by \`${spec.by}\`, which does not run in \`npm run build\`. A guard that ` +
        `has to be remembered has already failed twice in this repository.`,
    );
  }
}

// ── 4. NARRATIVE: contains no record of this product's *present* state ─────
for (const [f, spec] of Object.entries(DOCS)) {
  if (spec.kind !== 'NARRATIVE' || !files.includes(f)) continue;
  const text = readFileSync(join(ROOT, f), 'utf8');

  if (spec.historical) {
    /*
     * A stamped report is history and may hold every verdict it likes: it
     * describes a tree that is not this one, and a claim about a fixed commit
     * cannot become untrue. What it may not do is fail to say which commit —
     * an unstamped audit is claiming to describe the present, and the present
     * is the thing that moves.
     */
    const sha = /\*\*Describes commit `([0-9a-f]{7,40})`/.exec(text)?.[1];
    if (!sha) {
      fail(
        f,
        'is registered as history and does not say which commit it describes. Add ' +
          '"**Describes commit `<sha>`.**" near the top, or reclassify it.',
      );
    } else {
      try {
        execFileSync('git', ['cat-file', '-e', `${sha}^{commit}`], { stdio: 'ignore' });
      } catch {
        fail(f, `names commit \`${sha}\`, which is not in this repository.`);
      }
    }
    continue;
  }

  for (const r of stateRecords(text)) {
    fail(
      f,
      `line ${r.n} is ${r.why}, and this file is NARRATIVE — nothing checks it, so it will ` +
        `go wrong silently. Either move the claim to a GENERATED or GUARDED document, mark ` +
        `the file as history with the commit it describes, or delete it.\n      ${r.text}`,
    );
  }
}

// ── 5. The two documents this guard checks directly ────────────────────────
/**
 * The backlog: a ticket cannot be closed and open at once.
 *
 * PA-009, PA-012 and RA-006 were all closed while still listed as open work,
 * which is what "the RA backlog had three closed tickets it had not been told
 * about" means. The closed table names what closed each one; an id in that
 * table may not also head a row of the open tables.
 */
const backlogPath = 'docs/BACKLOG_MOTIONLAB.md';
if (files.includes(backlogPath)) {
  const text = readFileSync(join(ROOT, backlogPath), 'utf8');
  const closed = new Set();
  const open = new Set();
  let inClosedTable = false;
  for (const line of text.split('\n')) {
    if (/^\|\s*closed\s*\|/i.test(line)) inClosedTable = true;
    else if (/^\|\s*Id\s*\|/i.test(line)) inClosedTable = false;
    else if (/^#/.test(line)) inClosedTable = false;
    const id = /^\|\s*(?:~~)?([A-Z]{2}-\d{3})(?:~~)?\s*\|/.exec(line);
    if (!id) continue;
    // A struck id is a closure marked in place, which is the same statement.
    if (inClosedTable || line.includes(`~~${id[1]}~~`)) closed.add(id[1]);
    else open.add(id[1]);
  }
  const both = [...open].filter((id) => closed.has(id));
  if (both.length) {
    fail(
      backlogPath,
      `lists ${both.join(', ')} as both closed and open. This is the failure that let three ` +
        `closed tickets sit in the open list across a directive.`,
    );
  }
  if (closed.size === 0) {
    fail(backlogPath, 'has no closed-ticket table, so this check found nothing to compare.');
  }
}

/**
 * Known limitations: a limitation of code that is gone is a claim about nothing.
 *
 * Only paths that look like repo paths — a backticked token with a slash and a
 * file extension. A backticked identifier is prose about a symbol and is not
 * this guard's business.
 */
const limitsPath = 'docs/KNOWN-LIMITATIONS.md';
if (files.includes(limitsPath)) {
  const text = readFileSync(join(ROOT, limitsPath), 'utf8');
  const missing = [];
  for (const m of text.matchAll(/`((?:src|e2e|tests|scripts|motionwave|docs)\/[^`\s]+\.\w+)`/g)) {
    if (!existsSync(join(ROOT, m[1]))) missing.push(m[1]);
  }
  const unique = [...new Set(missing)];
  if (unique.length) {
    fail(limitsPath, `names files that no longer exist: ${unique.join(', ')}.`);
  }
}

// ── 6. The detector still detects ──────────────────────────────────────────
// Without this, emptying the patterns in `state.mjs` turns rule 4 green on
// every document at once and reads as "no document records state".
{
  const canary = [
    '| Granular Delay | `fx-03` | NOT STARTED |',
    '- [x] done',
    '**Status:** design only. No implementation exists here.',
  ].join('\n');
  const hits = stateRecords(canary);
  if (hits.length !== 3) {
    problems.push(
      `docs-guard self-test: the state detector found ${hits.length} of 3 planted records. ` +
        `Rule 4 is reporting clean because it has stopped looking.`,
    );
  }
  if (stateRecords('```\n| x | PASS |\n```').length !== 0) {
    problems.push('docs-guard self-test: a fenced code block was read as a record.');
  }
  if (!PATTERNS.VERDICT_CELL || !PATTERNS.CHECKBOX || !PATTERNS.IMPLEMENTATION_CLAIM) {
    problems.push('docs-guard self-test: a pattern is missing from state.mjs.');
  }
}

// ── Report ─────────────────────────────────────────────────────────────────
const counts = { GENERATED: 0, GUARDED: 0, NARRATIVE: 0 };
for (const f of files) if (DOCS[f]) counts[DOCS[f].kind]++;

for (const n of notes) console.log(`docs-guard: ${n}`);

if (problems.length) {
  console.error('');
  console.error(`docs-guard: ${problems.length} problem(s).`);
  console.error('');
  for (const p of problems) console.error(`  - ${p}`);
  console.error('');
  process.exit(1);
}

console.log(
  `docs-guard: ${files.length} documents — ${counts.GENERATED} generated, ` +
    `${counts.GUARDED} guarded, ${counts.NARRATIVE} narrative. None records unchecked state.`,
);
